#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
BNレコードパーサー: １７．馬主マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class BNParser:
    """
    BNレコードパーサー

    １７．馬主マスタ
    レコード長: 387 bytes
    VBテーブル名: BANUSI
    """

    RECORD_TYPE = "BN"
    RECORD_LENGTH = 387

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        BNレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"BNレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 馬主コード (位置:12, 長さ:6)
            result["BanusiCode"] = self.decode_field(data[11:17])

            # 5. 馬主名(法人格有) (位置:18, 長さ:64)
            result["BanusiName_Co"] = self.decode_field(data[17:81])

            # 6. 馬主名(法人格無) (位置:82, 長さ:64)
            result["BanusiName"] = self.decode_field(data[81:145])

            # 7. 馬主名半角ｶﾅ (位置:146, 長さ:50)
            result["BanusiNameKana"] = self.decode_field(data[145:195])

            # 8. 馬主名欧字 (位置:196, 長さ:100)
            result["BanusiNameEng"] = self.decode_field(data[195:295])

            # 9. 服色標示 (位置:296, 長さ:60)
            result["Fukusyoku"] = self.decode_field(data[295:355])

            # 10. <本年･累計成績情報> (位置:356, 長さ:0)
            # 11. 　　設定年 (位置:356, 長さ:4)
            result["SetYear"] = self.decode_field(data[355:359])

            # 12. 　　本賞金合計 (位置:360, 長さ:10)
            result["HonSyokinTotal"] = self.decode_field(data[359:369])

            # 13. 　　付加賞金合計 (位置:370, 長さ:10)
            result["FukaSyokin"] = self.decode_field(data[369:379])

            # 14. 　　着回数 (位置:380, 長さ:6)
            result["ChakuKaisu"] = self.decode_field(data[379:385])

            # 15. レコード区切 (位置:386, 長さ:2)
            result["Reserved_386"] = self.decode_field(data[385:387])

            return result

        except Exception as e:
            self.logger.error(f"BNレコードパース中にエラー: {e}")
            return None
