#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
BTレコードパーサー: ２６．系統情報

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import List
from src.parser.base import BaseParser, FieldDef


class BTParser(BaseParser):
    """
    BTレコードパーサー

    ２６．系統情報
    レコード長: 6889 bytes
    VBテーブル名: KEITO
    """

    record_type = "BT"

    def _define_fields(self) -> List[FieldDef]:
        """Define field positions for BT record.

        Returns:
            List of FieldDef objects
        """
        return [
            FieldDef("RecordSpec", 0, 2),        # レコード種別ID
            FieldDef("DataKubun", 2, 1),         # データ区分
            FieldDef("MakeDate", 3, 8),          # データ作成年月日
            FieldDef("HansyokuNum", 11, 10),     # 繁殖登録番号
            FieldDef("KeitoId", 21, 30),         # 系統ID
            FieldDef("KeitoName", 51, 36),       # 系統名
            FieldDef("KeitoEx", 87, 6800),       # 系統説明
            FieldDef("RecordDelimiter", 6887, 2),      # レコード区切
        ]
