#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
CSレコードパーサー: ２７．コース情報

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import List
from src.parser.base import BaseParser, FieldDef


class CSParser(BaseParser):
    """
    CSレコードパーサー

    ２７．コース情報
    レコード長: 6829 bytes
    VBテーブル名: COURSE
    """

    record_type = "CS"

    def _define_fields(self) -> List[FieldDef]:
        """Define field positions for CS record.

        Returns:
            List of FieldDef objects
        """
        return [
            FieldDef("RecordSpec", 0, 2),        # レコード種別ID
            FieldDef("DataKubun", 2, 1),         # データ区分
            FieldDef("MakeDate", 3, 8),          # データ作成年月日
            FieldDef("JyoCD", 11, 2),            # 競馬場コード
            FieldDef("Kyori", 13, 4),            # 距離
            FieldDef("TrackCD", 17, 2),          # トラックコード
            FieldDef("KaishuDate", 19, 8),       # コース改修年月日
            FieldDef("CourseEx", 27, 6800),      # コース説明
            FieldDef("RecordDelimiter", 6827, 2),      # レコード区切
        ]
