#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HCレコードパーサー: 調教師本年・累計成績

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HCParser:
    """
    HCレコードパーサー

    調教師本年・累計成績
    レコード長: 60 bytes
    VBテーブル名: CHOKYO_SEISEKI
    """

    RECORD_TYPE = "HC"
    RECORD_LENGTH = 60

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HCレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HCレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1-2, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4-11, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 調教師コード (位置:12-16, 長さ:5)
            result["ChokyosiCode"] = self.decode_field(data[11:16])

            # 5. 本年・累計区分 (位置:17-18, 長さ:2)
            result["Num"] = self.decode_field(data[16:18])

            # 6. 集計年 (位置:19-22, 長さ:4)
            result["SetYear"] = self.decode_field(data[18:22])

            # 7. 本賞金・平地 (位置:23-31, 長さ:9)
            result["HonSyokinHeichi"] = self.decode_field(data[22:31])

            # 8. 本賞金・障害 (位置:32-40, 長さ:9)
            result["HonSyokinSyogai"] = self.decode_field(data[31:40])

            # 9. 付加賞金・平地 (位置:41-49, 長さ:9)
            result["FukaSyokinHeichi"] = self.decode_field(data[40:49])

            # 10. 付加賞金・障害 (位置:50-58, 長さ:9)
            result["FukaSyokinSyogai"] = self.decode_field(data[49:58])

            # 11. レコード区切 (位置:59-60, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[58:60])

            return result

        except Exception as e:
            self.logger.error(f"HCレコードパース中にエラー: {e}")
            return None
