#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HNレコードパーサー: １８．繁殖馬マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HNParser:
    """
    HNレコードパーサー

    １８．繁殖馬マスタ
    レコード長: 251 bytes
    VBテーブル名: HANRO
    """

    RECORD_TYPE = "HN"
    RECORD_LENGTH = 251

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HNレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HNレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 繁殖登録番号 (位置:12, 長さ:8)
            result["HansyokuNum"] = self.decode_field(data[11:19])

            # 5. 予備 (位置:20, 長さ:1)
            result["reserved"] = self.decode_field(data[19:20])

            # 6. 血統登録番号 (位置:21, 長さ:10)
            result["KettoNum"] = self.decode_field(data[20:30])

            # 7. 削除区分 (位置:31, 長さ:1)
            result["DelKubun"] = self.decode_field(data[30:31])

            # 8. 馬名 (位置:32, 長さ:36)
            result["Bamei"] = self.decode_field(data[31:67])

            # 9. 馬名半角ｶﾅ (位置:68, 長さ:40)
            result["BameiKana"] = self.decode_field(data[67:107])

            # 10. 馬名欧字 (位置:108, 長さ:40)
            result["BameiEng"] = self.decode_field(data[107:147])

            # 11. 生年 (位置:148, 長さ:4)
            result["BirthYear"] = self.decode_field(data[147:151])

            # 12. 性別コード (位置:152, 長さ:1)
            result["SexCD"] = self.decode_field(data[151:152])

            # 13. 品種コード (位置:153, 長さ:1)
            result["HinsyuCD"] = self.decode_field(data[152:153])

            # 14. 毛色コード (位置:154, 長さ:2)
            result["KeiroCD"] = self.decode_field(data[153:155])

            # 15. 繁殖馬持込区分 (位置:156, 長さ:1)
            result["MochiKubun"] = self.decode_field(data[155:156])

            # 16. 輸入年 (位置:157, 長さ:4)
            result["ImportYear"] = self.decode_field(data[156:160])

            # 17. 産地名 (位置:161, 長さ:20)
            result["SanchiName"] = self.decode_field(data[160:180])

            # 18. 父馬繁殖登録番号 (位置:181, 長さ:8)
            result["FHansyokuNum"] = self.decode_field(data[180:188])

            # 19. 母馬繁殖登録番号 (位置:189, 長さ:8)
            result["MHansyokuNum"] = self.decode_field(data[188:196])

            # 20. 予備 (位置:197, 長さ:53)
            result["Reserved_197"] = self.decode_field(data[196:249])

            # 21. レコード区切 (位置:250, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[249:251])

            return result

        except Exception as e:
            self.logger.error(f"HNレコードパース中にエラー: {e}")
            return None
