#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HSレコードパーサー: ２３．競走馬市場取引価格

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HSParser:
    """
    HSレコードパーサー

    ２３．競走馬市場取引価格
    レコード長: 200 bytes
    VBテーブル名: SALE
    """

    RECORD_TYPE = "HS"
    RECORD_LENGTH = 200

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HSレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HSレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 血統登録番号 (位置:12, 長さ:10)
            result["KettoNum"] = self.decode_field(data[11:21])

            # 5. 父馬 繁殖登録番号 (位置:22, 長さ:10)
            result["HansyokuFNum"] = self.decode_field(data[21:31])

            # 6. 母馬 繁殖登録番号 (位置:32, 長さ:10)
            result["HansyokuMNum"] = self.decode_field(data[31:41])

            # 7. 生年 (位置:42, 長さ:4)
            result["BirthYear"] = self.decode_field(data[41:45])

            # 8. 主催者・市場コード (位置:46, 長さ:6)
            result["SaleCode"] = self.decode_field(data[45:51])

            # 9. 主催者名称 (位置:52, 長さ:40)
            result["SaleHostName"] = self.decode_field(data[51:91])

            # 10. 市場の名称 (位置:92, 長さ:80)
            result["SaleName"] = self.decode_field(data[91:171])

            # 11. 市場の開催期間(開始日) (位置:172, 長さ:8)
            result["FromDate"] = self.decode_field(data[171:179])

            # 12. 市場の開催期間(終了日) (位置:180, 長さ:8)
            result["ToDate"] = self.decode_field(data[179:187])

            # 13. 取引時の競走馬の年齢 (位置:188, 長さ:1)
            result["Barei"] = self.decode_field(data[187:188])

            # 14. 取引価格 (位置:189, 長さ:10)
            result["Price"] = self.decode_field(data[188:198])

            # 15. レコード区切 (位置:199, 長さ:2)
            result["Field15"] = self.decode_field(data[198:200])

            return result

        except Exception as e:
            self.logger.error(f"HSレコードパース中にエラー: {e}")
            return None
