#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HYレコードパーサー: ２４．馬名の意味由来

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class HYParser:
    """
    HYレコードパーサー

    ２４．馬名の意味由来
    レコード長: 123 bytes
    VBテーブル名: BAMEIORIGIN
    """

    RECORD_TYPE = "HY"
    RECORD_LENGTH = 123

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        HYレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"HYレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 血統登録番号 (位置:12, 長さ:10)
            result["Bamei"] = self.decode_field(data[11:21])

            # 5. 馬名 (位置:22, 長さ:36)
            result["Field5"] = self.decode_field(data[21:57])

            # 6. 馬名の意味由来 (位置:58, 長さ:64)
            result["Field6"] = self.decode_field(data[57:121])

            # 7. レコード区切 (位置:122, 長さ:2)
            result["Field7"] = self.decode_field(data[121:123])

            return result

        except Exception as e:
            self.logger.error(f"HYレコードパース中にエラー: {e}")
            return None
