#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
JGレコードパーサー: ３１．競走馬除外情報

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class JGParser:
    """
    JGレコードパーサー

    ３１．競走馬除外情報
    レコード長: 80 bytes
    VBテーブル名: TORIKESI_JYOGAI
    """

    RECORD_TYPE = "JG"
    RECORD_LENGTH = 80

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        JGレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"JGレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 血統登録番号 (位置:28, 長さ:10)
            result["KettoNum"] = self.decode_field(data[27:37])

            # 11. 馬名 (位置:38, 長さ:36)
            result["Bamei"] = self.decode_field(data[37:73])

            # 12. 出馬投票受付順番 (位置:74, 長さ:3)
            result["Num"] = self.decode_field(data[73:76])

            # 13. 出走区分 (位置:77, 長さ:1)
            result["SyussoKubun"] = self.decode_field(data[76:77])

            # 14. 除外状態区分 (位置:78, 長さ:1)
            result["JyogaiStateKubun"] = self.decode_field(data[77:78])

            # 15. レコード区切 (位置:79, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[78:80])

            return result

        except Exception as e:
            self.logger.error(f"JGレコードパース中にエラー: {e}")
            return None
