#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
KSレコードパーサー: １４．騎手マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class KSParser:
    """
    KSレコードパーサー

    １４．騎手マスタ
    レコード長: 772 bytes
    VBテーブル名: KISYU
    """

    RECORD_TYPE = "KS"
    RECORD_LENGTH = 772

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        KSレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"KSレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 騎手コード (位置:12, 長さ:5)
            result["KisyuCode"] = self.decode_field(data[11:16])

            # 5. 騎手抹消区分 (位置:17, 長さ:1)
            result["DelKubun"] = self.decode_field(data[16:17])

            # 6. 騎手免許交付年月日 (位置:18, 長さ:8)
            result["IssueDate"] = self.decode_field(data[17:25])

            # 7. 騎手免許抹消年月日 (位置:26, 長さ:8)
            result["DelDate"] = self.decode_field(data[25:33])

            # 8. 生年月日 (位置:34, 長さ:8)
            result["BirthDate"] = self.decode_field(data[33:41])

            # 9. 騎手名 (位置:42, 長さ:34)
            result["KisyuName"] = self.decode_field(data[41:75])

            # 10. 予備 (位置:76, 長さ:34)
            result["reserved"] = self.decode_field(data[75:109])

            # 11. 騎手名半角ｶﾅ (位置:110, 長さ:30)
            result["KisyuNameKana"] = self.decode_field(data[109:139])

            # 12. 騎手名略称 (位置:140, 長さ:8)
            result["KisyuRyakusyo"] = self.decode_field(data[139:147])

            # 13. 騎手名欧字 (位置:148, 長さ:80)
            result["KisyuNameEng"] = self.decode_field(data[147:227])

            # 14. 性別区分 (位置:228, 長さ:1)
            result["SexCD"] = self.decode_field(data[227:228])

            # 15. 騎乗資格コード (位置:229, 長さ:1)
            result["SikakuCD"] = self.decode_field(data[228:229])

            # 16. 騎手見習コード (位置:230, 長さ:1)
            result["MinaraiCD"] = self.decode_field(data[229:230])

            # 17. 騎手東西所属コード (位置:231, 長さ:1)
            result["TozaiCD"] = self.decode_field(data[230:231])

            # 18. 招待地域名 (位置:232, 長さ:20)
            result["Syotai"] = self.decode_field(data[231:251])

            # 19. 所属調教師コード (位置:252, 長さ:5)
            result["ChokyosiCode"] = self.decode_field(data[251:256])

            # 20. 所属調教師名略称 (位置:257, 長さ:8)
            result["ChokyosiRyakusyo"] = self.decode_field(data[256:264])

            # 21. <初騎乗情報> (位置:265, 長さ:0)
            # This is a section header with length 0, no field assigned

            # 22. 　　年月日場回日R (位置:265, 長さ:16)
            result["HatuKiJyo1Hatukijyoid"] = self.decode_field(data[264:280])

            # 23. 　　出走頭数 (位置:281, 長さ:2)
            result["HatuKiJyo1SyussoTosu"] = self.decode_field(data[280:282])

            # 24. 　　血統登録番号 (位置:283, 長さ:10)
            result["HatuKiJyo1KettoNum"] = self.decode_field(data[282:292])

            # 25. 　　馬名 (位置:293, 長さ:36)
            result["HatuKiJyo1Bamei"] = self.decode_field(data[292:328])

            # 26. 　　確定着順 (位置:329, 長さ:2)
            result["HatuKiJyo1KakuteiJyuni"] = self.decode_field(data[328:330])

            # 27. 　　異常区分コード (位置:331, 長さ:1)
            result["HatuKiJyo1IJyoCD"] = self.decode_field(data[330:331])

            # 28. <初勝利情報> (位置:332, 長さ:0)
            # This is a section header with length 0, no field assigned

            # 29. 　　年月日場回日R (位置:332, 長さ:16)
            result["HatuSyori1Hatusyoriid"] = self.decode_field(data[331:347])

            # 30. 　　出走頭数 (位置:348, 長さ:2)
            result["HatuSyori1SyussoTosu"] = self.decode_field(data[347:349])

            # 31. 　　血統登録番号 (位置:350, 長さ:10)
            result["HatuSyori1KettoNum"] = self.decode_field(data[349:359])

            # 32. 　　馬名 (位置:360, 長さ:36)
            result["HatuSyori1Bamei"] = self.decode_field(data[359:395])

            # 33. <最近重賞勝利情報> (位置:396, 長さ:0)
            # This is a section header with length 0, no field assigned

            # 34. 　　年月日場回日R (位置:396, 長さ:16)
            result["SaikinJyusyo1SaikinJyusyoid"] = self.decode_field(data[395:411])

            # 35. 　　競走名本題 (位置:412, 長さ:60)
            result["SaikinJyusyo1Hondai"] = self.decode_field(data[411:471])

            # 36. 　　競走名略称10文字 (位置:472, 長さ:20)
            result["SaikinJyusyo1Ryakusyo10"] = self.decode_field(data[471:491])

            # 37. 　　競走名略称6文字 (位置:492, 長さ:12)
            result["SaikinJyusyo1Ryakusyo6"] = self.decode_field(data[491:503])

            # 38. 　　競走名略称3文字 (位置:504, 長さ:6)
            result["SaikinJyusyo1Ryakusyo3"] = self.decode_field(data[503:509])

            # 39. 　　グレードコード (位置:510, 長さ:1)
            result["SaikinJyusyo1GradeCD"] = self.decode_field(data[509:510])

            # 40. 　　出走頭数 (位置:511, 長さ:2)
            result["SaikinJyusyo1SyussoTosu"] = self.decode_field(data[510:512])

            # 41. 　　血統登録番号 (位置:513, 長さ:10)
            result["SaikinJyusyo1KettoNum"] = self.decode_field(data[512:522])

            # 42. 　　馬名 (位置:523, 長さ:36)
            result["SaikinJyusyo1Bamei"] = self.decode_field(data[522:558])

            # 43. <初騎乗情報2> - 平地の初騎乗 (位置:559, 長さ:67)
            # 　　年月日場回日R (位置:559, 長さ:16)
            result["HatuKiJyo2Hatukijyoid"] = self.decode_field(data[558:574])
            # 　　出走頭数 (位置:575, 長さ:2)
            result["HatuKiJyo2SyussoTosu"] = self.decode_field(data[574:576])
            # 　　血統登録番号 (位置:577, 長さ:10)
            result["HatuKiJyo2KettoNum"] = self.decode_field(data[576:586])
            # 　　馬名 (位置:587, 長さ:36)
            result["HatuKiJyo2Bamei"] = self.decode_field(data[586:622])
            # 　　確定着順 (位置:623, 長さ:2)
            result["HatuKiJyo2KakuteiJyuni"] = self.decode_field(data[622:624])
            # 　　異常区分コード (位置:625, 長さ:1)
            result["HatuKiJyo2IJyoCD"] = self.decode_field(data[624:625])

            # 44. <初勝利情報2> - 平地の初勝利 (位置:626, 長さ:64)
            # 　　年月日場回日R (位置:626, 長さ:16)
            result["HatuSyori2Hatusyoriid"] = self.decode_field(data[625:641])
            # 　　出走頭数 (位置:642, 長さ:2)
            result["HatuSyori2SyussoTosu"] = self.decode_field(data[641:643])
            # 　　血統登録番号 (位置:644, 長さ:10)
            result["HatuSyori2KettoNum"] = self.decode_field(data[643:653])
            # 　　馬名 (位置:654, 長さ:36)
            result["HatuSyori2Bamei"] = self.decode_field(data[653:689])

            # 45-46. 予備領域 (位置:690, 長さ:81)
            # レコード長772バイトの制約により、最近重賞2と3のデータは含まれていない
            # スキーマとの整合性のため、空フィールドとして定義
            result["SaikinJyusyo2SaikinJyusyoid"] = ""
            result["SaikinJyusyo2Hondai"] = ""
            result["SaikinJyusyo2Ryakusyo10"] = ""
            result["SaikinJyusyo2Ryakusyo6"] = ""
            result["SaikinJyusyo2Ryakusyo3"] = ""
            result["SaikinJyusyo2GradeCD"] = ""
            result["SaikinJyusyo2SyussoTosu"] = ""
            result["SaikinJyusyo2KettoNum"] = ""
            result["SaikinJyusyo2Bamei"] = ""
            result["SaikinJyusyo3SaikinJyusyoid"] = ""
            result["SaikinJyusyo3Hondai"] = ""
            result["SaikinJyusyo3Ryakusyo10"] = ""
            result["SaikinJyusyo3Ryakusyo6"] = ""
            result["SaikinJyusyo3Ryakusyo3"] = ""
            result["SaikinJyusyo3GradeCD"] = ""
            result["SaikinJyusyo3SyussoTosu"] = ""
            result["SaikinJyusyo3KettoNum"] = ""
            result["SaikinJyusyo3Bamei"] = ""

            # 47. レコード区切 (位置:771, 長さ:2)
            result["crlf"] = self.decode_field(data[770:772])

            return result

        except Exception as e:
            self.logger.error(f"KSレコードパース中にエラー: {e}")
            return None
