#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
SEレコードパーサー: ３．馬毎レース情報

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class SEParser:
    """
    SEレコードパーサー

    ３．馬毎レース情報
    レコード長: 463 bytes
    VBテーブル名: UMA_RACE
    """

    RECORD_TYPE = "SE"
    RECORD_LENGTH = 463

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # CP932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        SEレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"SEレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 枠番 (位置:28, 長さ:1)
            result["Wakuban"] = self.decode_field(data[27:28])

            # 11. 馬番 (位置:29, 長さ:2)
            result["Umaban"] = self.decode_field(data[28:30])

            # 12. 血統登録番号 (位置:31, 長さ:10)
            result["KettoNum"] = self.decode_field(data[30:40])

            # 13. 馬名 (位置:41, 長さ:36)
            result["Bamei"] = self.decode_field(data[40:76])

            # 14. 馬記号コード (位置:77, 長さ:2)
            result["UmaKigoCD"] = self.decode_field(data[76:78])

            # 15. 性別コード (位置:79, 長さ:1)
            result["SexCD"] = self.decode_field(data[78:79])

            # 16. 品種コード (位置:80, 長さ:1)
            result["HinsyuCD"] = self.decode_field(data[79:80])

            # 17. 毛色コード (位置:81, 長さ:2)
            result["KeiroCD"] = self.decode_field(data[80:82])

            # 18. 馬齢 (位置:83, 長さ:2)
            result["Barei"] = self.decode_field(data[82:84])

            # 19. 東西所属コード (位置:85, 長さ:1)
            result["TozaiCD"] = self.decode_field(data[84:85])

            # 20. 調教師コード (位置:86, 長さ:5)
            result["ChokyosiCode"] = self.decode_field(data[85:90])

            # 21. 調教師名略称 (位置:91, 長さ:8)
            result["ChokyosiRyakusyo"] = self.decode_field(data[90:98])

            # 22. 馬主コード (位置:99, 長さ:6)
            result["BanusiCode"] = self.decode_field(data[98:104])

            # 23. 馬主名(法人格無) (位置:105, 長さ:64)
            result["BanusiName"] = self.decode_field(data[104:168])

            # 24. 服色標示 (位置:169, 長さ:60)
            result["Fukusyoku"] = self.decode_field(data[168:228])

            # 25. 予備 (位置:229, 長さ:60)
            result["Reserved_229"] = self.decode_field(data[228:288])

            # 26. 負担重量 (位置:289, 長さ:3)
            result["Futan"] = self.decode_field(data[288:291])

            # 27. 変更前負担重量 (位置:292, 長さ:3)
            result["FutanBefore"] = self.decode_field(data[291:294])

            # 28. ブリンカー使用区分 (位置:295, 長さ:1)
            result["Blinker"] = self.decode_field(data[294:295])

            # 29. 予備 (位置:296, 長さ:1)
            result["Reserved_296"] = self.decode_field(data[295:296])

            # 30. 騎手コード (位置:297, 長さ:5)
            result["KisyuCode"] = self.decode_field(data[296:301])

            # 31. 変更前騎手コード (位置:302, 長さ:5)
            result["KisyuCodeBefore"] = self.decode_field(data[301:306])

            # 32. 騎手名略称 (位置:307, 長さ:8)
            result["KisyuRyakusyo"] = self.decode_field(data[306:314])

            # 33. 変更前騎手名略称 (位置:315, 長さ:8)
            result["KisyuRyakusyoBefore"] = self.decode_field(data[314:322])

            # 34. 騎手見習コード (位置:323, 長さ:1)
            result["MinaraiCD"] = self.decode_field(data[322:323])

            # 35. 変更前騎手見習コード (位置:324, 長さ:1)
            result["MinaraiCDBefore"] = self.decode_field(data[323:324])

            # 36. 馬体重 (位置:325, 長さ:3)
            result["BaTaijyu"] = self.decode_field(data[324:327])

            # 37. 増減符号 (位置:328, 長さ:1)
            result["ZogenFugo"] = self.decode_field(data[327:328])

            # 38. 増減差 (位置:329, 長さ:3)
            result["ZogenSa"] = self.decode_field(data[328:331])

            # 39. 異常区分コード (位置:332, 長さ:1)
            result["IJyoCD"] = self.decode_field(data[331:332])

            # 40. 入線順位 (位置:333, 長さ:2)
            result["NyusenJyuni"] = self.decode_field(data[332:334])

            # 41. 確定着順 (位置:335, 長さ:2)
            result["KakuteiJyuni"] = self.decode_field(data[334:336])

            # 42. 同着区分 (位置:337, 長さ:1)
            result["DochakuKubun"] = self.decode_field(data[336:337])

            # 43. 同着頭数 (位置:338, 長さ:1)
            result["DochakuTosu"] = self.decode_field(data[337:338])

            # 44. 走破タイム (位置:339, 長さ:4)
            result["Time"] = self.decode_field(data[338:342])

            # 45. 着差コード (位置:343, 長さ:3)
            result["ChakusaCD"] = self.decode_field(data[342:345])

            # 46. ＋着差コード (位置:346, 長さ:3)
            result["ChakusaCDP"] = self.decode_field(data[345:348])

            # 47. ＋＋着差コード (位置:349, 長さ:3)
            result["ChakusaCDPP"] = self.decode_field(data[348:351])

            # 48. 1コーナーでの順位 (位置:352, 長さ:2)
            result["Jyuni1c"] = self.decode_field(data[351:353])

            # 49. 2コーナーでの順位 (位置:354, 長さ:2)
            result["Jyuni2c"] = self.decode_field(data[353:355])

            # 50. 3コーナーでの順位 (位置:356, 長さ:2)
            result["Jyuni3c"] = self.decode_field(data[355:357])

            # 51. 4コーナーでの順位 (位置:358, 長さ:2)
            result["Jyuni4c"] = self.decode_field(data[357:359])

            # 52. 単勝オッズ (位置:360, 長さ:4, 0.1倍単位, **** は確定後)
            odds_raw = self.decode_field(data[359:363])
            try:
                if not odds_raw or not odds_raw.strip() or '*' in odds_raw:
                    result["Odds"] = None
                else:
                    result["Odds"] = str(int(odds_raw) / 10)
            except (ValueError, TypeError):
                result["Odds"] = None

            # 53. 単勝人気順 (位置:364, 長さ:2)
            result["Ninki"] = self.decode_field(data[363:365])

            # 54. 獲得本賞金 (位置:366, 長さ:8)
            result["Honsyokin"] = self.decode_field(data[365:373])

            # 55. 獲得付加賞金 (位置:374, 長さ:8)
            result["Fukasyokin"] = self.decode_field(data[373:381])

            # 56. 予備 (位置:382, 長さ:3)
            result["Reserved_382"] = self.decode_field(data[381:384])

            # 57. 予備 (位置:385, 長さ:3)
            result["Reserved_385"] = self.decode_field(data[384:387])

            # 58. 後4ハロンタイム (位置:388, 長さ:3)
            result["HaronTimeL4"] = self.decode_field(data[387:390])

            # 59. 後3ハロンタイム (位置:391, 長さ:3)
            result["HaronTimeL3"] = self.decode_field(data[390:393])

            # 60. <1着馬(相手馬)情報> (位置:394, 繰返し3, 長さ:46×3=138)
            #     同着を考慮して繰返し3回。自身が1着の場合は2着馬を設定
            # 60a. 1着馬(1) 血統登録番号 (位置:394, 長さ:10)
            result["KettoNum1"] = self.decode_field(data[393:403])
            # 60b. 1着馬(1) 馬名 (位置:404, 長さ:36)
            result["Bamei1"] = self.decode_field(data[403:439])
            # 60c. 1着馬(2) 血統登録番号 (位置:440, 長さ:10)
            result["KettoNum2"] = self.decode_field(data[439:449])
            # 60d. 1着馬(2) 馬名 (位置:450, 長さ:36)
            result["Bamei2"] = self.decode_field(data[449:485])
            # 60e. 1着馬(3) 血統登録番号 (位置:486, 長さ:10)
            result["KettoNum3"] = self.decode_field(data[485:495])
            # 60f. 1着馬(3) 馬名 (位置:496, 長さ:36)
            result["Bamei3"] = self.decode_field(data[495:531])

            # 63. タイム差 (位置:532, 長さ:4)
            result["TimeDiff"] = self.decode_field(data[531:535])

            # 64. レコード更新区分 (位置:536, 長さ:1)
            result["RecordUpKubun"] = self.decode_field(data[535:536])

            # 65. マイニング区分 (位置:537, 長さ:1)
            result["DMKubun"] = self.decode_field(data[536:537])

            # 66. マイニング予想走破タイム (位置:538, 長さ:5)
            result["DMTime"] = self.decode_field(data[537:542])

            # 67. マイニング予想誤差(信頼度)＋ (位置:543, 長さ:4)
            result["DMGosaP"] = self.decode_field(data[542:546])

            # 68. マイニング予想誤差(信頼度)－ (位置:547, 長さ:4)
            result["DMGosaM"] = self.decode_field(data[546:550])

            # 69. マイニング予想順位 (位置:551, 長さ:2)
            result["DMJyuni"] = self.decode_field(data[550:552])

            # 70. 今回レース脚質判定 (位置:553, 長さ:1)
            result["KyakusituKubun"] = self.decode_field(data[552:553])

            # 71. レコード区切 (位置:554, 長さ:2)
            result["Reserved_462"] = self.decode_field(data[553:555])

            return result

        except Exception as e:
            self.logger.error(f"SEレコードパース中にエラー: {e}")
            return None
