#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
SKレコードパーサー: １９．産駒マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class SKParser:
    """
    SKレコードパーサー

    １９．産駒マスタ
    レコード長: 78 bytes
    VBテーブル名: SANKU
    """

    RECORD_TYPE = "SK"
    RECORD_LENGTH = 78

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # CP932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        SKレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"SKレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 血統登録番号 (位置:12, 長さ:10)
            result["KettoNum"] = self.decode_field(data[11:21])

            # 5. 生年月日 (位置:22, 長さ:8)
            result["BirthDate"] = self.decode_field(data[21:29])

            # 6. 性別コード (位置:30, 長さ:1)
            result["SexCD"] = self.decode_field(data[29:30])

            # 7. 品種コード (位置:31, 長さ:1)
            result["HinsyuCD"] = self.decode_field(data[30:31])

            # 8. 毛色コード (位置:32, 長さ:2)
            result["KeiroCD"] = self.decode_field(data[31:33])

            # 9. 産駒持込区分 (位置:34, 長さ:1)
            result["SankuMochiKubun"] = self.decode_field(data[33:34])

            # 10. 輸入年 (位置:35, 長さ:4)
            result["ImportYear"] = self.decode_field(data[34:38])

            # 11. 生産者コード (位置:39, 長さ:8)
            result["BreederCode"] = self.decode_field(data[38:46])

            # 12. 産地名 (位置:47, 長さ:20)
            result["SanchiName"] = self.decode_field(data[46:66])

            # 13. 父繁殖登録番号 (位置:67, 長さ:10)
            result["FNum"] = self.decode_field(data[66:76])

            # 14. レコード区切 (位置:77, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[76:78])

            return result

        except Exception as e:
            self.logger.error(f"SKレコードパース中にエラー: {e}")
            return None
