#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
TKレコードパーサー: １．特別登録馬

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class TKParser:
    """
    TKレコードパーサー

    １．特別登録馬
    レコード長: 727 bytes
    VBテーブル名: TOKU
    """

    RECORD_TYPE = "TK"
    RECORD_LENGTH = 727

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # CP932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        TKレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"TKレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 曜日コード (位置:28, 長さ:1)
            result["YoubiCD"] = self.decode_field(data[27:28])

            # 11. 特別競走番号 (位置:29, 長さ:4)
            result["TokuNum"] = self.decode_field(data[28:32])

            # 12. 競走名本題 (位置:33, 長さ:60)
            result["Hondai"] = self.decode_field(data[32:92])

            # 13. 競走名副題 (位置:93, 長さ:60)
            result["Fukudai"] = self.decode_field(data[92:152])

            # 14. 競走名カッコ内 (位置:153, 長さ:60)
            result["Kakko"] = self.decode_field(data[152:212])

            # 15. 競走名本題欧字 (位置:213, 長さ:120)
            result["HondaiEng"] = self.decode_field(data[212:332])

            # 16. 競走名副題欧字 (位置:333, 長さ:120)
            result["FukudaiEng"] = self.decode_field(data[332:452])

            # 17. 競走名カッコ内欧字 (位置:453, 長さ:120)
            result["KakkoEng"] = self.decode_field(data[452:572])

            # 18. 競走名略称10文字 (位置:573, 長さ:20)
            result["RaceRyakusyo10"] = self.decode_field(data[572:592])

            # 19. 競走名略称6文字 (位置:593, 長さ:12)
            result["RaceRyakusyo6"] = self.decode_field(data[592:604])

            # 20. 競走名略称3文字 (位置:605, 長さ:6)
            result["RaceRyakusyo3"] = self.decode_field(data[604:610])

            # 21. 競走名区分 (位置:611, 長さ:1)
            result["RaceMeiKubun"] = self.decode_field(data[610:611])

            # 22. 重賞回次[第N回] (位置:612, 長さ:3)
            result["JyusyoKaiji"] = self.decode_field(data[611:614])

            # 23. グレードコード (位置:615, 長さ:1)
            result["GradeCD"] = self.decode_field(data[614:615])

            # 24. 競走種別コード (位置:616, 長さ:2)
            result["SyubetuCD"] = self.decode_field(data[615:617])

            # 25. 競走記号コード (位置:618, 長さ:3)
            result["KigoCD"] = self.decode_field(data[617:620])

            # 26. 重量種別コード (位置:621, 長さ:1)
            result["JyuryoCD"] = self.decode_field(data[620:621])

            # 27. 競走条件コード 2歳条件 (位置:622, 長さ:3)
            result["JyokenCD2"] = self.decode_field(data[621:624])

            # 28. 競走条件コード 3歳条件 (位置:625, 長さ:3)
            result["JyokenCD3"] = self.decode_field(data[624:627])

            # 29. 競走条件コード 4歳条件 (位置:628, 長さ:3)
            result["JyokenCD4"] = self.decode_field(data[627:630])

            # 30. 競走条件コード 5歳以上条件 (位置:631, 長さ:3)
            result["JyokenCD5"] = self.decode_field(data[630:633])

            # 31. 競走条件コード 最若年条件 (位置:634, 長さ:3)
            result["JyokenCDYoung"] = self.decode_field(data[633:636])

            # 32. 距離 (位置:637, 長さ:4)
            result["Kyori"] = self.decode_field(data[636:640])

            # 33. トラックコード (位置:641, 長さ:2)
            result["TrackCD"] = self.decode_field(data[640:642])

            # 34. コース区分 (位置:643, 長さ:2)
            result["CourseKubun"] = self.decode_field(data[642:644])

            # 35. ハンデ発表日 (位置:645, 長さ:8)
            result["HandeHappyoDate"] = self.decode_field(data[644:652])

            # 36. 登録頭数 (位置:653, 長さ:3)
            result["TorokuTosu"] = self.decode_field(data[652:655])

            # 37. <登録馬毎情報> (位置:656, 長さ:0)
            # Note: This is a header for repeating horse registration data, no actual data to extract

            # 38. 　　連番 (位置:656, 長さ:3)
            result["RenbanNum"] = self.decode_field(data[655:658])

            # 39. 　　血統登録番号 (位置:659, 長さ:10)
            result["KettoNum"] = self.decode_field(data[658:668])

            # 40. 　　馬名 (位置:669, 長さ:36)
            result["Bamei"] = self.decode_field(data[668:704])

            # 41. 　　馬記号コード (位置:705, 長さ:2)
            result["UmaKigoCD"] = self.decode_field(data[704:706])

            # 42. 　　性別コード (位置:707, 長さ:1)
            result["SexCD"] = self.decode_field(data[706:707])

            # 43. 　　調教師東西所属コード (位置:708, 長さ:1)
            result["TozaiCD"] = self.decode_field(data[707:708])

            # 44. 　　調教師コード (位置:709, 長さ:5)
            result["ChokyosiCode"] = self.decode_field(data[708:713])

            # 45. 　　調教師名略称 (位置:714, 長さ:8)
            result["ChokyosiRyakusyo"] = self.decode_field(data[713:721])

            # 46. 　　負担重量 (位置:722, 長さ:3)
            result["Futan"] = self.decode_field(data[721:724])

            # 47. 　　交流区分 (位置:725, 長さ:1)
            result["Koryu"] = self.decode_field(data[724:725])

            # 48-51. 　　連番002-300情報 (位置:726, 長さ:0)
            # Note: These are placeholders for additional horse entries (not present in single-entry records)

            # 52. レコード区切 (位置:726, 長さ:2)
            result["RecordBreak"] = self.decode_field(data[725:727])

            return result

        except Exception as e:
            self.logger.error(f"TKレコードパース中にエラー: {e}")
            return None
