#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
YSレコードパーサー: ２５．開催スケジュール

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class YSParser:
    """
    YSレコードパーサー

    ２５．開催スケジュール
    レコード長: 146 bytes
    VBテーブル名: SCHEDULE
    """

    RECORD_TYPE = "YS"
    RECORD_LENGTH = 146

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # CP932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        YSレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"YSレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. 曜日コード (位置:26, 長さ:1)
            result["YoubiCD"] = self.decode_field(data[25:26])

            # 10. 特別競走番号 (位置:27, 長さ:4)
            result["Jyusyo1TokuNum"] = self.decode_field(data[26:30])

            # 11. 競走名本題 (位置:31, 長さ:60)
            result["Jyusyo1Hondai"] = self.decode_field(data[30:90])

            # 12. 競走名略称10文字 (位置:91, 長さ:20)
            result["Jyusyo1Ryakusyo10"] = self.decode_field(data[90:110])

            # 13. 競走名略称6文字 (位置:111, 長さ:12)
            result["Jyusyo1Ryakusyo6"] = self.decode_field(data[110:122])

            # 14. 競走名略称3文字 (位置:123, 長さ:6)
            result["Jyusyo1Ryakusyo3"] = self.decode_field(data[122:128])

            # 15. 重賞回次[第N回] (位置:129, 長さ:3)
            result["Jyusyo1Nkai"] = self.decode_field(data[128:131])

            # 16. グレードコード (位置:132, 長さ:1)
            result["Jyusyo1GradeCD"] = self.decode_field(data[131:132])

            # 17. 競走種別コード (位置:133, 長さ:2)
            result["Jyusyo1SyubetuCD"] = self.decode_field(data[132:134])

            # 18. 競走記号コード (位置:135, 長さ:3)
            result["Jyusyo1KigoCD"] = self.decode_field(data[134:137])

            # 19. 重量種別コード (位置:138, 長さ:1)
            result["Jyusyo1JyuryoCD"] = self.decode_field(data[137:138])

            # 20. 距離 (位置:139, 長さ:4)
            result["Jyusyo1Kyori"] = self.decode_field(data[138:142])

            # 21. トラックコード (位置:143, 長さ:2)
            result["Jyusyo1TrackCD"] = self.decode_field(data[142:144])

            # 22. レコード区切 (位置:145, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[144:146])

            return result

        except Exception as e:
            self.logger.error(f"YSレコードパース中にエラー: {e}")
            return None
