"""Database schema manager for JLTSQL.

Optimized schema with appropriate data types for SQLite.
Auto-generated from JV-Data official specification.

Generated by: scripts/generate_simple_schema.py
Source: 公式JV-Data仕様書 Ver.4.9.0.1

Data Type Optimization:
- INTEGER: Year, MonthDay, Kaiji, Nichiji, RaceNum, Umaban, Kyori, counts, flags
- NUMERIC(p,s): Odds, Time, Haron times (exact decimal, no float rounding)
- INTEGER/BIGINT: Weights (kg), prize money
- TEXT: Codes (fixed-length), dates (YYYYMMDD), names

IMPORTANT - Duplicate Handling & Primary Keys:
==============================================

Current Status:
- ALL 58 tables now have PRIMARY KEY constraints defined
- INSERT OR REPLACE is used by default in the importer
- WITH primary keys, duplicate records will be UPDATED instead of created

Primary Keys Implemented:
-------------------------
Race-related Tables:
    NL_RA, RT_RA: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_SE, RT_SE: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_RC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, RecInfoKubun)
    NL_TK: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
    NL_YS: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji)

Master Tables:
    NL_UM: PRIMARY KEY (KettoNum)  -- Horse registration number
    NL_SK: PRIMARY KEY (KettoNum)  -- Horse production
    NL_KS: PRIMARY KEY (KisyuCode)  -- Jockey code
    NL_CH: PRIMARY KEY (ChokyosiCode)  -- Trainer code
    NL_BN: PRIMARY KEY (BanusiCode)  -- Owner code
    NL_BR: PRIMARY KEY (BreederCode)  -- Breeder code
    NL_BT: PRIMARY KEY (HansyokuNum)  -- Breeding lineage
    NL_HN: PRIMARY KEY (HansyokuNum)  -- Breeding horse
    NL_CS: PRIMARY KEY (JyoCD, Kyori, TrackCD)  -- Course

Odds Tables:
    NL_O1, RT_O1: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_O1_WAKU, RT_O1_WAKU: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O2, RT_O2: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O3, RT_O3: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O4, RT_O4: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O5, RT_O5: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
    NL_O6, RT_O6: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)

Payout Tables:
    NL_H1, RT_H1: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, BetType, Kumi)
    NL_H6, RT_H6: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, SanrentanKumi)
    NL_HR, RT_HR: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)

Additional Data Tables:
    NL_CK: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
    NL_HC: PRIMARY KEY (ChokyosiCode, Num, SetYear)
    NL_TM, RT_TM: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_WF: PRIMARY KEY (Year, MonthDay)

Change Information Tables:
    NL_CC, RT_CC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_JC, RT_JC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
    NL_TC, RT_TC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
    NL_JG: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
    RT_RC: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)

Weather/Track Condition Tables:
    NL_WE, RT_WE: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HenkoID)
    NL_WH, RT_WH: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)

Pace/Data Mining Tables:
    NL_DM, RT_DM: PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)

Sale/Auction Tables:
    NL_AV, RT_AV: PRIMARY KEY (KettoNum, SaleHostName, SaleName)
    NL_HS: PRIMARY KEY (KettoNum, SaleCode, FromDate)

Workout/Training Tables:
    NL_SLOP: PRIMARY KEY (TresenKubun, ChokyoDate, ChokyoTime, KettoNum)
    NL_WC: PRIMARY KEY (ChokyoDate, ChokyoTime, KettoNum, Course)

Horse Name Table:
    NL_HY: PRIMARY KEY (Bamei)

Benefits with PRIMARY KEY constraints:
- INSERT OR REPLACE will update existing records instead of duplicating
- Safe to re-run imports multiple times
- Better data integrity and referential consistency
- Prevents duplicate records on re-import
- Optimized query performance on primary key columns
"""

from typing import Dict, List

from src.database.base import BaseDatabase
from src.utils.logger import get_logger

logger = get_logger(__name__)


SCHEMAS = {
    "NL_BN": """
        CREATE TABLE IF NOT EXISTS NL_BN (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            BanusiCode TEXT,
            BanusiName_Co TEXT,
            BanusiName TEXT,
            BanusiNameKana TEXT,
            BanusiNameEng TEXT,
            Fukusyoku TEXT,
            SetYear INTEGER,
            HonSyokinTotal BIGINT,
            FukaSyokin BIGINT,
            ChakuKaisu INTEGER,
            Reserved_386 TEXT,
            PRIMARY KEY (BanusiCode)
        )
    """,
    "NL_BR": """
        CREATE TABLE IF NOT EXISTS NL_BR (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            BreederCode TEXT,
            BreederName_Co TEXT,
            BreederName TEXT,
            BreederNameKana TEXT,
            BreederNameEng TEXT,
            Address TEXT,
            SetYear INTEGER,
            HonSyokinTotal BIGINT,
            FukaSyokin BIGINT,
            ChakuKaisu INTEGER,
            Reserved_454 TEXT,
            PRIMARY KEY (BreederCode)
        )
    """,
    "NL_BT": """
        CREATE TABLE IF NOT EXISTS NL_BT (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            HansyokuNum TEXT,
            KeitoId TEXT,
            KeitoName TEXT,
            KeitoEx TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (HansyokuNum)
        )
    """,

    "NL_AV": """
        CREATE TABLE IF NOT EXISTS NL_AV (
            RecordSpec TEXT,
            DataKubun TEXT,
            KettoNum TEXT,
            SaleHostName TEXT,
            SaleName TEXT,
            Price BIGINT,
            RecordDelimiter TEXT,
            PRIMARY KEY (KettoNum, SaleHostName, SaleName)
        )
    """,

    "NL_CC": """
        CREATE TABLE IF NOT EXISTS NL_CC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HappyoTime TEXT,
            AtoKyori INTEGER,
            AtoTruckCD TEXT,
            MaeKyori INTEGER,
            MaeTruckCD TEXT,
            JiyuCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,

    "NL_CK": """
        CREATE TABLE IF NOT EXISTS NL_CK (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            HeichiHonsyokinTotal BIGINT,
            SyogaiHonsyokinTotal BIGINT,
            HeichiFukasyokinTotal BIGINT,
            SyogaiFukasyokinTotal BIGINT,
            HeichiSyutokuTotal BIGINT,
            SyogaiSyutokuTotal BIGINT,
            TotalChakuCount INTEGER,
            ChuoChakuCount INTEGER,
            SibaChoChaku INTEGER,
            SibaMigiChaku INTEGER,
            SibaHidariChaku INTEGER,
            DirtChoChaku INTEGER,
            DirtMigiChaku INTEGER,
            DirtHidariChaku INTEGER,
            SyogaiChaku INTEGER,
            SibaRyoChaku INTEGER,
            SibaYayaChaku INTEGER,
            SibaOmoChaku INTEGER,
            SibaFuChaku INTEGER,
            DirtRyoChaku INTEGER,
            DirtYayaChaku INTEGER,
            DirtOmoChaku INTEGER,
            DirtFuChaku INTEGER,
            SyogaiRyoChaku INTEGER,
            SyogaiYayaChaku INTEGER,
            SyogaiOmoChaku INTEGER,
            SyogaiFuChaku INTEGER,
            Siba1200IkaChaku INTEGER,
            Siba1201_1400Chaku INTEGER,
            Siba1401_1600Chaku INTEGER,
            Siba1601_1800Chaku INTEGER,
            Siba1801_2000Chaku INTEGER,
            Siba2001_2200Chaku INTEGER,
            Siba2201_2400Chaku INTEGER,
            Siba2401_2800Chaku INTEGER,
            Siba2801OverChaku INTEGER,
            Dirt1200IkaChaku INTEGER,
            Dirt1201_1400Chaku INTEGER,
            Dirt1401_1600Chaku INTEGER,
            Dirt1601_1800Chaku INTEGER,
            Dirt1801_2000Chaku INTEGER,
            Dirt2001_2200Chaku INTEGER,
            Dirt2201_2400Chaku INTEGER,
            Dirt2401_2800Chaku INTEGER,
            Dirt2801OverChaku INTEGER,
            SapporoSibaChaku INTEGER,
            HakodateSibaChaku INTEGER,
            FukushimaSibaChaku INTEGER,
            NiigataSibaChaku INTEGER,
            TokyoSibaChaku INTEGER,
            NakayamaSibaChaku INTEGER,
            ChukyoSibaChaku INTEGER,
            KyotoSibaChaku INTEGER,
            HanshinSibaChaku INTEGER,
            KokuraSibaChaku INTEGER,
            SapporoDirtChaku INTEGER,
            HakodateDirtChaku INTEGER,
            FukushimaDirtChaku INTEGER,
            NiigataDirtChaku INTEGER,
            TokyoDirtChaku INTEGER,
            NakayamaDirtChaku INTEGER,
            ChukyoDirtChaku INTEGER,
            KyotoDirtChaku INTEGER,
            HanshinDirtChaku INTEGER,
            KokuraDirtChaku INTEGER,
            SapporoSyogaiChaku INTEGER,
            HakodateSyogaiChaku INTEGER,
            FukushimaSyogaiChaku INTEGER,
            NiigataSyogaiChaku INTEGER,
            TokyoSyogaiChaku INTEGER,
            NakayamaSyogaiChaku INTEGER,
            ChukyoSyogaiChaku INTEGER,
            KyotoSyogaiChaku INTEGER,
            HanshinSyogaiChaku INTEGER,
            KokuraSyogaiChaku INTEGER,
            NigeCount SMALLINT,
            SenkoCount SMALLINT,
            SashiCount SMALLINT,
            OikomiCount SMALLINT,
            RegisteredRaceCount INTEGER,
            KisyuCode TEXT,
            KisyuName TEXT,
            KisyuResultsInfo TEXT,
            ChokyosiCode TEXT,
            ChokyosiName TEXT,
            ChokyosiResultsInfo TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            BanusiName_Co TEXT,
            BanusiResultsInfo TEXT,
            BreederCode TEXT,
            BreederName TEXT,
            BreederName_Co TEXT,
            BreederResultsInfo TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
        )
    """,
    "NL_CH": """
        CREATE TABLE IF NOT EXISTS NL_CH (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            ChokyosiCode TEXT,
            DelKubun TEXT,
            IssueDate TEXT,
            DelDate TEXT,
            BirthDate TEXT,
            ChokyosiName TEXT,
            ChokyosiNameKana TEXT,
            ChokyosiRyakusyo TEXT,
            ChokyosiNameEng TEXT,
            SexCD TEXT,
            TozaiCD TEXT,
            Syotai TEXT,
            SaikinJyusyo1_id TEXT,
            SaikinJyusyo1_Hondai TEXT,
            SaikinJyusyo1_Ryakusyo10 TEXT,
            SaikinJyusyo1_Ryakusyo6 TEXT,
            SaikinJyusyo1_Ryakusyo3 TEXT,
            SaikinJyusyo1_GradeCD TEXT,
            SaikinJyusyo1_SyussoTosu INTEGER,
            SaikinJyusyo1_KettoNum TEXT,
            SaikinJyusyo1_Bamei TEXT,
            SetYear INTEGER,
            HonSyokinH BIGINT,
            HonSyokinS BIGINT,
            FukaSyokinH BIGINT,
            FukaSyokinS BIGINT,
            ChakuKaisuH INTEGER,
            ChakuKaisuS INTEGER,
            ChakuKaisu01H INTEGER,
            ChakuKaisu01S INTEGER,
            ChakuKaisu02H INTEGER,
            ChakuKaisu02S INTEGER,
            ChakuKaisu03H INTEGER,
            ChakuKaisu03S INTEGER,
            ChakuKaisu04H INTEGER,
            ChakuKaisu04S INTEGER,
            ChakuKaisu05H INTEGER,
            ChakuKaisu05S INTEGER,
            ChakuKaisu06H INTEGER,
            ChakuKaisu06S INTEGER,
            ChakuKaisu07H INTEGER,
            ChakuKaisu07S INTEGER,
            ChakuKaisu08H INTEGER,
            ChakuKaisu08S INTEGER,
            ChakuKaisu09H INTEGER,
            ChakuKaisu09S INTEGER,
            ChakuKaisu10H INTEGER,
            ChakuKaisu10S INTEGER,
            ChakuKaisuSiba1 INTEGER,
            ChakuKaisuSiba2 INTEGER,
            ChakuKaisuSiba3 INTEGER,
            ChakuKaisuDirt1 INTEGER,
            ChakuKaisuDirt2 INTEGER,
            ChakuKaisuDirt3 INTEGER,
            Reserved_591 TEXT,
            PRIMARY KEY (ChokyosiCode)
        )
    """,
    "NL_CS": """
        CREATE TABLE IF NOT EXISTS NL_CS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            JyoCD TEXT,
            Kyori INTEGER,
            TrackCD TEXT,
            KaishuDate TEXT,
            CourseEx TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (JyoCD, Kyori, TrackCD)
        )
    """,
    "NL_DM": """
        CREATE TABLE IF NOT EXISTS NL_DM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            MakeHM TEXT,
            Umaban INTEGER,
            DMTime TEXT,
            DMGosaP TEXT,
            DMGosaM TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_H1": """
        CREATE TABLE IF NOT EXISTS NL_H1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag1 TEXT,
            HatubaiFlag2 TEXT,
            HatubaiFlag3 TEXT,
            HatubaiFlag4 TEXT,
            HatubaiFlag5 TEXT,
            HatubaiFlag6 TEXT,
            HatubaiFlag7 TEXT,
            FukuChakuBaraiKey TEXT,
            HenkanUma TEXT,
            HenkanWaku TEXT,
            HenkanDoWaku TEXT,
            BetType TEXT,
            Kumi TEXT,
            Hyo BIGINT,
            Ninki INTEGER,
            TanHyoTotal BIGINT,
            FukuHyoTotal BIGINT,
            WakuHyoTotal BIGINT,
            UmarenHyoTotal BIGINT,
            WideHyoTotal BIGINT,
            UmatanHyoTotal BIGINT,
            SanrenfukuHyoTotal BIGINT,
            TanHenkanHyoTotal BIGINT,
            FukuHenkanHyoTotal BIGINT,
            WakuHenkanHyoTotal BIGINT,
            UmarenHenkanHyoTotal BIGINT,
            WideHenkanHyoTotal BIGINT,
            UmatanHenkanHyoTotal BIGINT,
            SanrenfukuHenkanHyoTotal BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, BetType, Kumi)
        )
    """,
    "NL_H6": """
        CREATE TABLE IF NOT EXISTS NL_H6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag TEXT,
            HenkanUma TEXT,
            SanrentanKumi TEXT,
            SanrentanHyo BIGINT,
            SanrentanNinki INTEGER,
            SanrentanHyoTotal BIGINT,
            SanrentanHenkanHyoTotal BIGINT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, SanrentanKumi)
        )
    """,
    "NL_HC": """
        CREATE TABLE IF NOT EXISTS NL_HC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            ChokyosiCode TEXT,
            Num INTEGER,
            SetYear INTEGER,
            HonSyokinHeichi BIGINT,
            HonSyokinSyogai BIGINT,
            FukaSyokinHeichi BIGINT,
            FukaSyokinSyogai BIGINT,
            RecordDelimiter TEXT,
            PRIMARY KEY (ChokyosiCode, Num, SetYear)
        )
    """,
    "NL_HN": """
        CREATE TABLE IF NOT EXISTS NL_HN (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            HansyokuNum TEXT,
            reserved TEXT,
            KettoNum TEXT,
            DelKubun TEXT,
            Bamei TEXT,
            BameiKana TEXT,
            BameiEng TEXT,
            BirthYear INTEGER,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            MochiKubun TEXT,
            ImportYear INTEGER,
            SanchiName TEXT,
            FHansyokuNum TEXT,
            MHansyokuNum TEXT,
            Reserved_197 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (HansyokuNum)
        )
    """,
    "NL_HR": """
        CREATE TABLE IF NOT EXISTS NL_HR (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            FuseirituFlag1 INTEGER,
            FuseirituFlag2 INTEGER,
            FuseirituFlag3 INTEGER,
            FuseirituFlag4 INTEGER,
            FuseirituFlag5 INTEGER,
            FuseirituFlag6 INTEGER,
            FuseirituFlag7 INTEGER,
            FuseirituFlag8 INTEGER,
            FuseirituFlag9 INTEGER,
            TokubaraiFlag1 INTEGER,
            TokubaraiFlag2 INTEGER,
            TokubaraiFlag3 INTEGER,
            TokubaraiFlag4 INTEGER,
            TokubaraiFlag5 INTEGER,
            TokubaraiFlag6 INTEGER,
            TokubaraiFlag7 INTEGER,
            TokubaraiFlag8 INTEGER,
            TokubaraiFlag9 INTEGER,
            HenkanFlag1 INTEGER,
            HenkanFlag2 INTEGER,
            HenkanFlag3 INTEGER,
            HenkanFlag4 INTEGER,
            HenkanFlag5 INTEGER,
            HenkanFlag6 INTEGER,
            HenkanFlag7 INTEGER,
            HenkanFlag8 INTEGER,
            HenkanFlag9 INTEGER,
            HenkanUma1 TEXT,
            HenkanUma2 TEXT,
            HenkanUma3 TEXT,
            HenkanUma4 TEXT,
            HenkanUma5 TEXT,
            HenkanUma6 TEXT,
            HenkanUma7 TEXT,
            HenkanUma8 TEXT,
            HenkanUma9 TEXT,
            HenkanUma10 TEXT,
            HenkanUma11 TEXT,
            HenkanUma12 TEXT,
            HenkanUma13 TEXT,
            HenkanUma14 TEXT,
            HenkanUma15 TEXT,
            HenkanUma16 TEXT,
            HenkanUma17 TEXT,
            HenkanUma18 TEXT,
            HenkanUma19 TEXT,
            HenkanUma20 TEXT,
            HenkanUma21 TEXT,
            HenkanUma22 TEXT,
            HenkanUma23 TEXT,
            HenkanUma24 TEXT,
            HenkanUma25 TEXT,
            HenkanUma26 TEXT,
            HenkanUma27 TEXT,
            HenkanUma28 TEXT,
            HenkanWaku1 TEXT,
            HenkanWaku2 TEXT,
            HenkanWaku3 TEXT,
            HenkanWaku4 TEXT,
            HenkanWaku5 TEXT,
            HenkanWaku6 TEXT,
            HenkanWaku7 TEXT,
            HenkanWaku8 TEXT,
            HenkanDoWaku1 TEXT,
            HenkanDoWaku2 TEXT,
            HenkanDoWaku3 TEXT,
            HenkanDoWaku4 TEXT,
            HenkanDoWaku5 TEXT,
            HenkanDoWaku6 TEXT,
            HenkanDoWaku7 TEXT,
            HenkanDoWaku8 TEXT,
            TanUmaban TEXT,
            TanPay BIGINT,
            TanNinki INTEGER,
            TanUmaban2 TEXT,
            TanPay2 BIGINT,
            TanNinki2 INTEGER,
            TanUmaban3 TEXT,
            TanPay3 BIGINT,
            TanNinki3 INTEGER,
            FukuUmaban TEXT,
            FukuPay BIGINT,
            FukuNinki INTEGER,
            FukuUmaban2 TEXT,
            FukuPay2 BIGINT,
            FukuNinki2 INTEGER,
            FukuUmaban3 TEXT,
            FukuPay3 BIGINT,
            FukuNinki3 INTEGER,
            FukuUmaban4 TEXT,
            FukuPay4 BIGINT,
            FukuNinki4 INTEGER,
            FukuUmaban5 TEXT,
            FukuPay5 BIGINT,
            FukuNinki5 INTEGER,
            WakuKumi TEXT,
            WakuPay BIGINT,
            WakuNinki INTEGER,
            WakuKumi2 TEXT,
            WakuPay2 BIGINT,
            WakuNinki2 INTEGER,
            WakuKumi3 TEXT,
            WakuPay3 BIGINT,
            WakuNinki3 INTEGER,
            UmarenKumi TEXT,
            UmarenPay BIGINT,
            UmarenNinki INTEGER,
            UmarenKumi2 TEXT,
            UmarenPay2 BIGINT,
            UmarenNinki2 INTEGER,
            UmarenKumi3 TEXT,
            UmarenPay3 BIGINT,
            UmarenNinki3 INTEGER,
            WideKumi TEXT,
            WidePay BIGINT,
            WideNinki INTEGER,
            WideKumi2 TEXT,
            WidePay2 BIGINT,
            WideNinki2 INTEGER,
            WideKumi3 TEXT,
            WidePay3 BIGINT,
            WideNinki3 INTEGER,
            WideKumi4 TEXT,
            WidePay4 BIGINT,
            WideNinki4 INTEGER,
            WideKumi5 TEXT,
            WidePay5 BIGINT,
            WideNinki5 INTEGER,
            WideKumi6 TEXT,
            WidePay6 BIGINT,
            WideNinki6 INTEGER,
            WideKumi7 TEXT,
            WidePay7 BIGINT,
            WideNinki7 INTEGER,
            UmatanKumi TEXT,
            UmatanPay BIGINT,
            UmatanNinki INTEGER,
            UmatanKumi2 TEXT,
            UmatanPay2 BIGINT,
            UmatanNinki2 INTEGER,
            UmatanKumi3 TEXT,
            UmatanPay3 BIGINT,
            UmatanNinki3 INTEGER,
            UmatanKumi4 TEXT,
            UmatanPay4 BIGINT,
            UmatanNinki4 INTEGER,
            UmatanKumi5 TEXT,
            UmatanPay5 BIGINT,
            UmatanNinki5 INTEGER,
            UmatanKumi6 TEXT,
            UmatanPay6 BIGINT,
            UmatanNinki6 INTEGER,
            SanrenfukuKumi TEXT,
            SanrenfukuPay BIGINT,
            SanrenfukuNinki INTEGER,
            SanrenfukuKumi2 TEXT,
            SanrenfukuPay2 BIGINT,
            SanrenfukuNinki2 INTEGER,
            SanrenfukuKumi3 TEXT,
            SanrenfukuPay3 BIGINT,
            SanrenfukuNinki3 INTEGER,
            SanrentanKumi TEXT,
            SanrentanPay BIGINT,
            SanrentanNinki INTEGER,
            SanrentanKumi2 TEXT,
            SanrentanPay2 BIGINT,
            SanrentanNinki2 INTEGER,
            SanrentanKumi3 TEXT,
            SanrentanPay3 BIGINT,
            SanrentanNinki3 INTEGER,
            SanrentanKumi4 TEXT,
            SanrentanPay4 BIGINT,
            SanrentanNinki4 INTEGER,
            SanrentanKumi5 TEXT,
            SanrentanPay5 BIGINT,
            SanrentanNinki5 INTEGER,
            SanrentanKumi6 TEXT,
            SanrentanPay6 BIGINT,
            SanrentanNinki6 INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_HS": """
        CREATE TABLE IF NOT EXISTS NL_HS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KettoNum TEXT,
            HansyokuFNum TEXT,
            HansyokuMNum TEXT,
            BirthYear INTEGER,
            SaleCode TEXT,
            SaleHostName TEXT,
            SaleName TEXT,
            FromDate TEXT,
            ToDate TEXT,
            Barei INTEGER,
            Price BIGINT,
            Field15 TEXT,
            PRIMARY KEY (KettoNum, SaleCode, FromDate)
        )
    """,
    "NL_HY": """
        CREATE TABLE IF NOT EXISTS NL_HY (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Bamei TEXT,
            Field5 TEXT,
            Field6 TEXT,
            Field7 TEXT,
            PRIMARY KEY (Bamei)
        )
    """,
    "NL_JG": """
        CREATE TABLE IF NOT EXISTS NL_JG (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            Num TEXT,
            SyussoKubun TEXT,
            JyogaiStateKubun TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
        )
    """,

    "NL_JC": """
        CREATE TABLE IF NOT EXISTS NL_JC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HappyoTime TEXT,
            Umaban INTEGER,
            Bamei TEXT,
            AtoFutan NUMERIC(4,1),
            AtoKisyuCode TEXT,
            AtoKisyuName TEXT,
            AtoMinaraiCD TEXT,
            MaeFutan NUMERIC(4,1),
            MaeKisyuCode TEXT,
            MaeKisyuName TEXT,
            MaeMinaraiCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_KS": """
        CREATE TABLE IF NOT EXISTS NL_KS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KisyuCode TEXT,
            DelKubun TEXT,
            IssueDate TEXT,
            DelDate TEXT,
            BirthDate TEXT,
            KisyuName TEXT,
            reserved TEXT,
            KisyuNameKana TEXT,
            KisyuRyakusyo TEXT,
            KisyuNameEng TEXT,
            SexCD TEXT,
            SikakuCD TEXT,
            MinaraiCD TEXT,
            TozaiCD TEXT,
            Syotai TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            HatuKiJyo1Hatukijyoid TEXT,
            HatuKiJyo1SyussoTosu INTEGER,
            HatuKiJyo1KettoNum TEXT,
            HatuKiJyo1Bamei TEXT,
            HatuKiJyo1KakuteiJyuni INTEGER,
            HatuKiJyo1IJyoCD TEXT,
            HatuKiJyo2Hatukijyoid TEXT,
            HatuKiJyo2SyussoTosu INTEGER,
            HatuKiJyo2KettoNum TEXT,
            HatuKiJyo2Bamei TEXT,
            HatuKiJyo2KakuteiJyuni INTEGER,
            HatuKiJyo2IJyoCD TEXT,
            HatuSyori1Hatusyoriid TEXT,
            HatuSyori1SyussoTosu INTEGER,
            HatuSyori1KettoNum TEXT,
            HatuSyori1Bamei TEXT,
            HatuSyori2Hatusyoriid TEXT,
            HatuSyori2SyussoTosu INTEGER,
            HatuSyori2KettoNum TEXT,
            HatuSyori2Bamei TEXT,
            SaikinJyusyo1SaikinJyusyoid TEXT,
            SaikinJyusyo1Hondai TEXT,
            SaikinJyusyo1Ryakusyo10 TEXT,
            SaikinJyusyo1Ryakusyo6 TEXT,
            SaikinJyusyo1Ryakusyo3 TEXT,
            SaikinJyusyo1GradeCD TEXT,
            SaikinJyusyo1SyussoTosu INTEGER,
            SaikinJyusyo1KettoNum TEXT,
            SaikinJyusyo1Bamei TEXT,
            SaikinJyusyo2SaikinJyusyoid TEXT,
            SaikinJyusyo2Hondai TEXT,
            SaikinJyusyo2Ryakusyo10 TEXT,
            SaikinJyusyo2Ryakusyo6 TEXT,
            SaikinJyusyo2Ryakusyo3 TEXT,
            SaikinJyusyo2GradeCD TEXT,
            SaikinJyusyo2SyussoTosu INTEGER,
            SaikinJyusyo2KettoNum TEXT,
            SaikinJyusyo2Bamei TEXT,
            SaikinJyusyo3SaikinJyusyoid TEXT,
            SaikinJyusyo3Hondai TEXT,
            SaikinJyusyo3Ryakusyo10 TEXT,
            SaikinJyusyo3Ryakusyo6 TEXT,
            SaikinJyusyo3Ryakusyo3 TEXT,
            SaikinJyusyo3GradeCD TEXT,
            SaikinJyusyo3SyussoTosu INTEGER,
            SaikinJyusyo3KettoNum TEXT,
            SaikinJyusyo3Bamei TEXT,
            crlf TEXT,
            PRIMARY KEY (KisyuCode)
        )
    """,
    "NL_O1": """
        CREATE TABLE IF NOT EXISTS NL_O1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            TanFlag TEXT,
            FukuFlag TEXT,
            WakurenFlag TEXT,
            FukuChakubaraiKey TEXT,
            Umaban INTEGER,
            TanOdds NUMERIC(8,1),
            TanNinki INTEGER,
            FukuUmaban INTEGER,
            FukuOddsLow NUMERIC(8,1),
            FukuOddsHigh NUMERIC(8,1),
            FukuNinki INTEGER,
            Kumi TEXT,
            WakurenOdds NUMERIC(8,1),
            WakurenNinki INTEGER,
            TanVote BIGINT,
            FukuVote BIGINT,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_O1_WAKU": """
        CREATE TABLE IF NOT EXISTS NL_O1_WAKU (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            WakurenFlag TEXT,
            Kumi TEXT,
            WakurenOdds NUMERIC(8,1),
            WakurenNinki INTEGER,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O2": """
        CREATE TABLE IF NOT EXISTS NL_O2 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmarenFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O3": """
        CREATE TABLE IF NOT EXISTS NL_O3 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            WideFlag TEXT,
            Kumi TEXT,
            OddsLow NUMERIC(8,1),
            OddsHigh NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O4": """
        CREATE TABLE IF NOT EXISTS NL_O4 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmatanFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O5": """
        CREATE TABLE IF NOT EXISTS NL_O5 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrenpukuFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_O6": """
        CREATE TABLE IF NOT EXISTS NL_O6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrentanFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_RA": """
        CREATE TABLE IF NOT EXISTS NL_RA (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            YoubiCD TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            Fukudai TEXT,
            Kakko TEXT,
            HondaiEng TEXT,
            FukudaiEng TEXT,
            KakkoEng TEXT,
            Ryakusyo10 TEXT,
            Ryakusyo6 TEXT,
            Ryakusyo3 TEXT,
            Kubun TEXT,
            Nkai TEXT,
            GradeCD TEXT,
            GradeCDBefore TEXT,
            SyubetuCD TEXT,
            KigoCD TEXT,
            JyuryoCD TEXT,
            JyokenCD1 TEXT,
            JyokenCD2 TEXT,
            JyokenCD3 TEXT,
            JyokenCD4 TEXT,
            JyokenCD5 TEXT,
            JyokenName TEXT,
            Kyori INTEGER,
            KyoriBefore INTEGER,
            TrackCD TEXT,
            TrackCDBefore TEXT,
            CourseKubunCD TEXT,
            CourseKubunCDBefore TEXT,
            Honsyokin1 BIGINT,
            Honsyokin2 BIGINT,
            Honsyokin3 BIGINT,
            Honsyokin4 BIGINT,
            Honsyokin5 BIGINT,
            Honsyokin6 BIGINT,
            Honsyokin7 BIGINT,
            HonsyokinBefore1 BIGINT,
            HonsyokinBefore2 BIGINT,
            HonsyokinBefore3 BIGINT,
            HonsyokinBefore4 BIGINT,
            HonsyokinBefore5 BIGINT,
            Fukasyokin1 BIGINT,
            Fukasyokin2 BIGINT,
            Fukasyokin3 BIGINT,
            Fukasyokin4 BIGINT,
            Fukasyokin5 BIGINT,
            FukasyokinBefore1 BIGINT,
            FukasyokinBefore2 BIGINT,
            FukasyokinBefore3 BIGINT,
            HassoTime TEXT,
            HassoTimeBefore TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            NyusenTosu INTEGER,
            TenkoCD TEXT,
            SibaBabaCD TEXT,
            DirtBabaCD TEXT,
            LapTime1 TEXT, LapTime2 TEXT, LapTime3 TEXT, LapTime4 TEXT, LapTime5 TEXT,
            LapTime6 TEXT, LapTime7 TEXT, LapTime8 TEXT, LapTime9 TEXT, LapTime10 TEXT,
            LapTime11 TEXT, LapTime12 TEXT, LapTime13 TEXT, LapTime14 TEXT, LapTime15 TEXT,
            LapTime16 TEXT, LapTime17 TEXT, LapTime18 TEXT, LapTime19 TEXT, LapTime20 TEXT,
            LapTime21 TEXT, LapTime22 TEXT, LapTime23 TEXT, LapTime24 TEXT, LapTime25 TEXT,
            SyogaiMileTime TEXT,
            Haron3F NUMERIC(4,1),
            Haron4F NUMERIC(4,1),
            Haron3L NUMERIC(4,1),
            Haron4L NUMERIC(4,1),
            Corner1 TEXT, Syukaisu1 TEXT, TsukaJyuni1 TEXT,
            Corner2 TEXT, Syukaisu2 TEXT, TsukaJyuni2 TEXT,
            Corner3 TEXT, Syukaisu3 TEXT, TsukaJyuni3 TEXT,
            Corner4 TEXT, Syukaisu4 TEXT, TsukaJyuni4 TEXT,
            RecordUpKubun TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_RC": """
        CREATE TABLE IF NOT EXISTS NL_RC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            RecInfoKubun TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TokuNum TEXT,
            Hondai TEXT,
            GradeCD TEXT,
            SyubetuCD_TrackCD TEXT,
            Kyori INTEGER,
            RecKubun TEXT,
            RecTime NUMERIC(5,1),
            TenkoCD TEXT,
            SibaBabaCD TEXT,
            DirtBabaCD TEXT,
            RecUmaKettoNum1 TEXT,
            RecUmaBamei1 TEXT,
            RecUmaUmaKigoCD1 TEXT,
            RecUmaSexCD1 TEXT,
            RecUmaChokyosiCode1 TEXT,
            RecUmaChokyosiName1 TEXT,
            RecUmaFutan1 NUMERIC(4,1),
            RecUmaKisyuCode1 TEXT,
            RecUmaKisyuName1 TEXT,
            RecUmaKettoNum2 TEXT,
            RecUmaBamei2 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, RecInfoKubun)
        )
    """,
    "NL_SE": """
        CREATE TABLE IF NOT EXISTS NL_SE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            Wakuban INTEGER,
            Umaban INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            Barei INTEGER,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            Fukusyoku TEXT,
            Reserved_229 TEXT,
            Futan NUMERIC(4,1),
            FutanBefore NUMERIC(4,1),
            Blinker TEXT,
            Reserved_296 TEXT,
            KisyuCode TEXT,
            KisyuCodeBefore TEXT,
            KisyuRyakusyo TEXT,
            KisyuRyakusyoBefore TEXT,
            MinaraiCD TEXT,
            MinaraiCDBefore TEXT,
            BaTaijyu INTEGER,
            ZogenFugo TEXT,
            ZogenSa INTEGER,
            IJyoCD TEXT,
            NyusenJyuni INTEGER,
            KakuteiJyuni INTEGER,
            DochakuKubun TEXT,
            DochakuTosu INTEGER,
            Time NUMERIC(5,1),
            ChakusaCD TEXT,
            ChakusaCDP TEXT,
            ChakusaCDPP TEXT,
            Jyuni1c INTEGER,
            Jyuni2c INTEGER,
            Jyuni3c INTEGER,
            Jyuni4c INTEGER,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Honsyokin BIGINT,
            Fukasyokin BIGINT,
            Reserved_382 TEXT,
            Reserved_385 TEXT,
            HaronTimeL4 NUMERIC(4,1),
            HaronTimeL3 NUMERIC(4,1),
            KettoNum1 TEXT,
            Bamei1 TEXT,
            KettoNum2 TEXT,
            Bamei2 TEXT,
            KettoNum3 TEXT,
            Bamei3 TEXT,
            TimeDiff NUMERIC(5,1),
            RecordUpKubun TEXT,
            DMKubun TEXT,
            DMTime NUMERIC(6,1),
            DMGosaP NUMERIC(5,1),
            DMGosaM NUMERIC(5,1),
            DMJyuni INTEGER,
            KyakusituKubun TEXT,
            Reserved_462 TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_SK": """
        CREATE TABLE IF NOT EXISTS NL_SK (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KettoNum TEXT,
            BirthDate TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            SankuMochiKubun TEXT,
            ImportYear INTEGER,
            BreederCode TEXT,
            SanchiName TEXT,
            FNum TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (KettoNum)
        )
    """,

    "NL_TC": """
        CREATE TABLE IF NOT EXISTS NL_TC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HappyoTime TEXT,
            AtoJi TEXT,
            AtoFun TEXT,
            MaeJi TEXT,
            MaeFun TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "NL_TK": """
        CREATE TABLE IF NOT EXISTS NL_TK (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            YoubiCD TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            Fukudai TEXT,
            Kakko TEXT,
            HondaiEng TEXT,
            FukudaiEng TEXT,
            KakkoEng TEXT,
            RaceRyakusyo10 TEXT,
            RaceRyakusyo6 TEXT,
            RaceRyakusyo3 TEXT,
            RaceMeiKubun TEXT,
            JyusyoKaiji INTEGER,
            GradeCD TEXT,
            SyubetuCD TEXT,
            KigoCD TEXT,
            JyuryoCD TEXT,
            JyokenCD2 TEXT,
            JyokenCD3 TEXT,
            JyokenCD4 TEXT,
            JyokenCD5 TEXT,
            JyokenCDYoung TEXT,
            Kyori INTEGER,
            TrackCD TEXT,
            CourseKubun TEXT,
            HandeHappyoDate TEXT,
            TorokuTosu INTEGER,
            RenbanNum INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            Futan NUMERIC(4,1),
            Koryu TEXT,
            RecordBreak TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, KettoNum)
        )
    """,
    "NL_TM": """
        CREATE TABLE IF NOT EXISTS NL_TM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            MakeHM TEXT,
            Umaban INTEGER,
            TMScore INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "NL_UM": """
        CREATE TABLE IF NOT EXISTS NL_UM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KettoNum TEXT,
            DelKubun TEXT,
            RegDate TEXT,
            DelDate TEXT,
            BirthDate TEXT,
            Bamei TEXT,
            BameiKana TEXT,
            BameiEng TEXT,
            ZaikyuFlag INTEGER,
            Reserved TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            Ketto3InfoHansyokuNum1 TEXT,
            Ketto3InfoBamei1 TEXT,
            Ketto3InfoHansyokuNum2 TEXT,
            Ketto3InfoBamei2 TEXT,
            Ketto3InfoHansyokuNum3 TEXT,
            Ketto3InfoBamei3 TEXT,
            Ketto3InfoHansyokuNum4 TEXT,
            Ketto3InfoBamei4 TEXT,
            Ketto3InfoHansyokuNum5 TEXT,
            Ketto3InfoBamei5 TEXT,
            Ketto3InfoHansyokuNum6 TEXT,
            Ketto3InfoBamei6 TEXT,
            Ketto3InfoHansyokuNum7 TEXT,
            Ketto3InfoBamei7 TEXT,
            Ketto3InfoHansyokuNum8 TEXT,
            Ketto3InfoBamei8 TEXT,
            Ketto3InfoHansyokuNum9 TEXT,
            Ketto3InfoBamei9 TEXT,
            Ketto3InfoHansyokuNum10 TEXT,
            Ketto3InfoBamei10 TEXT,
            Ketto3InfoHansyokuNum11 TEXT,
            Ketto3InfoBamei11 TEXT,
            Ketto3InfoHansyokuNum12 TEXT,
            Ketto3InfoBamei12 TEXT,
            Ketto3InfoHansyokuNum13 TEXT,
            Ketto3InfoBamei13 TEXT,
            Ketto3InfoHansyokuNum14 TEXT,
            Ketto3InfoBamei14 TEXT,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            Syotai TEXT,
            BreederCode TEXT,
            BreederName TEXT,
            SanchiName TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            RuikeiHonsyoHeiti BIGINT,
            RuikeiHonsyoSyogai BIGINT,
            RuikeiFukaHeichi BIGINT,
            RuikeiFukaSyogai BIGINT,
            RuikeiSyutokuHeichi BIGINT,
            RuikeiSyutokuSyogai BIGINT,
            SogoChakukaisu1 INTEGER,
            SogoChakukaisu2 INTEGER,
            SogoChakukaisu3 INTEGER,
            SogoChakukaisu4 INTEGER,
            SogoChakukaisu5 INTEGER,
            SogoChakukaisu6 INTEGER,
            ChuoChakukaisu1 INTEGER,
            ChuoChakukaisu2 INTEGER,
            ChuoChakukaisu3 INTEGER,
            ChuoChakukaisu4 INTEGER,
            ChuoChakukaisu5 INTEGER,
            ChuoChakukaisu6 INTEGER,
            Ba1Chakukaisu1 INTEGER,
            Ba1Chakukaisu2 INTEGER,
            Ba1Chakukaisu3 INTEGER,
            Ba1Chakukaisu4 INTEGER,
            Ba1Chakukaisu5 INTEGER,
            Ba1Chakukaisu6 INTEGER,
            Ba2Chakukaisu1 INTEGER,
            Ba2Chakukaisu2 INTEGER,
            Ba2Chakukaisu3 INTEGER,
            Ba2Chakukaisu4 INTEGER,
            Ba2Chakukaisu5 INTEGER,
            Ba2Chakukaisu6 INTEGER,
            Ba3Chakukaisu1 INTEGER,
            Ba3Chakukaisu2 INTEGER,
            Ba3Chakukaisu3 INTEGER,
            Ba3Chakukaisu4 INTEGER,
            Ba3Chakukaisu5 INTEGER,
            Ba3Chakukaisu6 INTEGER,
            Ba4Chakukaisu1 INTEGER,
            Ba4Chakukaisu2 INTEGER,
            Ba4Chakukaisu3 INTEGER,
            Ba4Chakukaisu4 INTEGER,
            Ba4Chakukaisu5 INTEGER,
            Ba4Chakukaisu6 INTEGER,
            Ba5Chakukaisu1 INTEGER,
            Ba5Chakukaisu2 INTEGER,
            Ba5Chakukaisu3 INTEGER,
            Ba5Chakukaisu4 INTEGER,
            Ba5Chakukaisu5 INTEGER,
            Ba5Chakukaisu6 INTEGER,
            Ba6Chakukaisu1 INTEGER,
            Ba6Chakukaisu2 INTEGER,
            Ba6Chakukaisu3 INTEGER,
            Ba6Chakukaisu4 INTEGER,
            Ba6Chakukaisu5 INTEGER,
            Ba6Chakukaisu6 INTEGER,
            Ba7Chakukaisu1 INTEGER,
            Ba7Chakukaisu2 INTEGER,
            Ba7Chakukaisu3 INTEGER,
            Ba7Chakukaisu4 INTEGER,
            Ba7Chakukaisu5 INTEGER,
            Ba7Chakukaisu6 INTEGER,
            Jyotai1Chakukaisu1 INTEGER,
            Jyotai1Chakukaisu2 INTEGER,
            Jyotai1Chakukaisu3 INTEGER,
            Jyotai1Chakukaisu4 INTEGER,
            Jyotai1Chakukaisu5 INTEGER,
            Jyotai1Chakukaisu6 INTEGER,
            Jyotai2Chakukaisu1 INTEGER,
            Jyotai2Chakukaisu2 INTEGER,
            Jyotai2Chakukaisu3 INTEGER,
            Jyotai2Chakukaisu4 INTEGER,
            Jyotai2Chakukaisu5 INTEGER,
            Jyotai2Chakukaisu6 INTEGER,
            Jyotai3Chakukaisu1 INTEGER,
            Jyotai3Chakukaisu2 INTEGER,
            Jyotai3Chakukaisu3 INTEGER,
            Jyotai3Chakukaisu4 INTEGER,
            Jyotai3Chakukaisu5 INTEGER,
            Jyotai3Chakukaisu6 INTEGER,
            Jyotai4Chakukaisu1 INTEGER,
            Jyotai4Chakukaisu2 INTEGER,
            Jyotai4Chakukaisu3 INTEGER,
            Jyotai4Chakukaisu4 INTEGER,
            Jyotai4Chakukaisu5 INTEGER,
            Jyotai4Chakukaisu6 INTEGER,
            Jyotai5Chakukaisu1 INTEGER,
            Jyotai5Chakukaisu2 INTEGER,
            Jyotai5Chakukaisu3 INTEGER,
            Jyotai5Chakukaisu4 INTEGER,
            Jyotai5Chakukaisu5 INTEGER,
            Jyotai5Chakukaisu6 INTEGER,
            Jyotai6Chakukaisu1 INTEGER,
            Jyotai6Chakukaisu2 INTEGER,
            Jyotai6Chakukaisu3 INTEGER,
            Jyotai6Chakukaisu4 INTEGER,
            Jyotai6Chakukaisu5 INTEGER,
            Jyotai6Chakukaisu6 INTEGER,
            Jyotai7Chakukaisu1 INTEGER,
            Jyotai7Chakukaisu2 INTEGER,
            Jyotai7Chakukaisu3 INTEGER,
            Jyotai7Chakukaisu4 INTEGER,
            Jyotai7Chakukaisu5 INTEGER,
            Jyotai7Chakukaisu6 INTEGER,
            Jyotai8Chakukaisu1 INTEGER,
            Jyotai8Chakukaisu2 INTEGER,
            Jyotai8Chakukaisu3 INTEGER,
            Jyotai8Chakukaisu4 INTEGER,
            Jyotai8Chakukaisu5 INTEGER,
            Jyotai8Chakukaisu6 INTEGER,
            Jyotai9Chakukaisu1 INTEGER,
            Jyotai9Chakukaisu2 INTEGER,
            Jyotai9Chakukaisu3 INTEGER,
            Jyotai9Chakukaisu4 INTEGER,
            Jyotai9Chakukaisu5 INTEGER,
            Jyotai9Chakukaisu6 INTEGER,
            Jyotai10Chakukaisu1 INTEGER,
            Jyotai10Chakukaisu2 INTEGER,
            Jyotai10Chakukaisu3 INTEGER,
            Jyotai10Chakukaisu4 INTEGER,
            Jyotai10Chakukaisu5 INTEGER,
            Jyotai10Chakukaisu6 INTEGER,
            Jyotai11Chakukaisu1 INTEGER,
            Jyotai11Chakukaisu2 INTEGER,
            Jyotai11Chakukaisu3 INTEGER,
            Jyotai11Chakukaisu4 INTEGER,
            Jyotai11Chakukaisu5 INTEGER,
            Jyotai11Chakukaisu6 INTEGER,
            Jyotai12Chakukaisu1 INTEGER,
            Jyotai12Chakukaisu2 INTEGER,
            Jyotai12Chakukaisu3 INTEGER,
            Jyotai12Chakukaisu4 INTEGER,
            Jyotai12Chakukaisu5 INTEGER,
            Jyotai12Chakukaisu6 INTEGER,
            Kyori1Chakukaisu1 INTEGER,
            Kyori1Chakukaisu2 INTEGER,
            Kyori1Chakukaisu3 INTEGER,
            Kyori1Chakukaisu4 INTEGER,
            Kyori1Chakukaisu5 INTEGER,
            Kyori1Chakukaisu6 INTEGER,
            Kyori2Chakukaisu1 INTEGER,
            Kyori2Chakukaisu2 INTEGER,
            Kyori2Chakukaisu3 INTEGER,
            Kyori2Chakukaisu4 INTEGER,
            Kyori2Chakukaisu5 INTEGER,
            Kyori2Chakukaisu6 INTEGER,
            Kyori3Chakukaisu1 INTEGER,
            Kyori3Chakukaisu2 INTEGER,
            Kyori3Chakukaisu3 INTEGER,
            Kyori3Chakukaisu4 INTEGER,
            Kyori3Chakukaisu5 INTEGER,
            Kyori3Chakukaisu6 INTEGER,
            Kyori4Chakukaisu1 INTEGER,
            Kyori4Chakukaisu2 INTEGER,
            Kyori4Chakukaisu3 INTEGER,
            Kyori4Chakukaisu4 INTEGER,
            Kyori4Chakukaisu5 INTEGER,
            Kyori4Chakukaisu6 INTEGER,
            Kyori5Chakukaisu1 INTEGER,
            Kyori5Chakukaisu2 INTEGER,
            Kyori5Chakukaisu3 INTEGER,
            Kyori5Chakukaisu4 INTEGER,
            Kyori5Chakukaisu5 INTEGER,
            Kyori5Chakukaisu6 INTEGER,
            Kyori6Chakukaisu1 INTEGER,
            Kyori6Chakukaisu2 INTEGER,
            Kyori6Chakukaisu3 INTEGER,
            Kyori6Chakukaisu4 INTEGER,
            Kyori6Chakukaisu5 INTEGER,
            Kyori6Chakukaisu6 INTEGER,
            Kyakusitu1 INTEGER,
            Kyakusitu2 INTEGER,
            Kyakusitu3 INTEGER,
            Kyakusitu4 INTEGER,
            TorokuRacesu INTEGER,
            PRIMARY KEY (KettoNum)
        )
    """,

    "NL_SLOP": """
        CREATE TABLE IF NOT EXISTS NL_SLOP (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            TresenKubun TEXT,
            ChokyoDate TEXT,
            ChokyoTime TEXT,
            KettoNum TEXT,
            HaronTime4Total NUMERIC(5,1),
            LapTime_800M_600M NUMERIC(4,1),
            HaronTime3Total NUMERIC(5,1),
            LapTime_600M_400M NUMERIC(4,1),
            HaronTime2Total NUMERIC(5,1),
            LapTime_400M_200M NUMERIC(4,1),
            LapTime_200M_0M NUMERIC(4,1),
            RecordDelimiter TEXT,
            PRIMARY KEY (TresenKubun, ChokyoDate, ChokyoTime, KettoNum)
        )
    """,

    "NL_WC": """
        CREATE TABLE IF NOT EXISTS NL_WC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            TresenKubun TEXT,
            ChokyoDate TEXT,
            ChokyoTime TEXT,
            KettoNum TEXT,
            Course TEXT,
            BabaMawari TEXT,
            reserved TEXT,
            HaronTime10Total NUMERIC(5,1),
            LapTime_2000M_1800M NUMERIC(4,1),
            HaronTime9Total NUMERIC(5,1),
            LapTime_1800M_1600M NUMERIC(4,1),
            HaronTime8Total NUMERIC(5,1),
            LapTime_1600M_1400M NUMERIC(4,1),
            HaronTime7Total NUMERIC(5,1),
            LapTime_1400M_1200M NUMERIC(4,1),
            HaronTime6Total NUMERIC(5,1),
            LapTime_1200M_1000M NUMERIC(4,1),
            HaronTime5Total NUMERIC(5,1),
            LapTime_1000M_800M NUMERIC(4,1),
            HaronTime4Total NUMERIC(5,1),
            LapTime_800M_600M NUMERIC(4,1),
            HaronTime3Total NUMERIC(5,1),
            LapTime_600M_400M NUMERIC(4,1),
            HaronTime2Total NUMERIC(5,1),
            LapTime_400M_200M NUMERIC(4,1),
            LapTime_200M_0M NUMERIC(4,1),
            RecordDelimiter TEXT,
            PRIMARY KEY (ChokyoDate, ChokyoTime, KettoNum, Course)
        )
    """,

    "NL_WE": """
        CREATE TABLE IF NOT EXISTS NL_WE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            HappyoTime TEXT,
            HenkoID TEXT,
            TenkoState TEXT,
            SibaBabaState TEXT,
            DirtBabaState TEXT,
            TenkoState2 TEXT,
            SibaBabaState2 TEXT,
            DirtBabaState2 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HenkoID)
        )
    """,

    "NL_WH": """
        CREATE TABLE IF NOT EXISTS NL_WH (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            HappyoTime TEXT,
            HenkoID TEXT,
            AtoTenkoCD TEXT,
            AtoSibaBabaCD TEXT,
            AtoDirtBabaCD TEXT,
            MaeTenkoCD TEXT,
            MaeSibaBabaCD TEXT,
            MaeDirtBabaCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)
        )
    """,
    "NL_WF": """
        CREATE TABLE IF NOT EXISTS NL_WF (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            Yobi1 TEXT,
            RaceInfo1 TEXT,
            RaceInfo2 TEXT,
            RaceInfo3 TEXT,
            RaceInfo4 TEXT,
            RaceInfo5 TEXT,
            Yobi2 TEXT,
            HatubaiHyosu BIGINT,
            YukoHyosu BIGINT,
            YukoHyosu2 BIGINT,
            YukoHyosu3 BIGINT,
            YukoHyosu4 BIGINT,
            YukoHyosu5 BIGINT,
            HenkanFlag TEXT,
            FuseirituFlag TEXT,
            TekichuNasiFlag TEXT,
            CarryOverStart BIGINT,
            CarryOverBalance BIGINT,
            Kumi TEXT,
            PayJyushosiki BIGINT,
            TekichuHyosu BIGINT,
            Kumi2 TEXT,
            PayJyushosiki2 BIGINT,
            TekichuHyosu2 BIGINT,
            Kumi3 TEXT,
            PayJyushosiki3 BIGINT,
            TekichuHyosu3 BIGINT,
            Kumi4 TEXT,
            PayJyushosiki4 BIGINT,
            TekichuHyosu4 BIGINT,
            Kumi5 TEXT,
            PayJyushosiki5 BIGINT,
            TekichuHyosu5 BIGINT,
            Kumi6 TEXT,
            PayJyushosiki6 BIGINT,
            TekichuHyosu6 BIGINT,
            Kumi7 TEXT,
            PayJyushosiki7 BIGINT,
            TekichuHyosu7 BIGINT,
            Kumi8 TEXT,
            PayJyushosiki8 BIGINT,
            TekichuHyosu8 BIGINT,
            Kumi9 TEXT,
            PayJyushosiki9 BIGINT,
            TekichuHyosu9 BIGINT,
            Kumi10 TEXT,
            PayJyushosiki10 BIGINT,
            TekichuHyosu10 BIGINT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay)
        )
    """,
    "NL_YS": """
        CREATE TABLE IF NOT EXISTS NL_YS (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            YoubiCD TEXT,
            Jyusyo1TokuNum INTEGER,
            Jyusyo1Hondai TEXT,
            Jyusyo1Ryakusyo10 TEXT,
            Jyusyo1Ryakusyo6 TEXT,
            Jyusyo1Ryakusyo3 TEXT,
            Jyusyo1Nkai INTEGER,
            Jyusyo1GradeCD TEXT,
            Jyusyo1SyubetuCD TEXT,
            Jyusyo1KigoCD TEXT,
            Jyusyo1JyuryoCD TEXT,
            Jyusyo1Kyori INTEGER,
            Jyusyo1TrackCD TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji)
        )
    """,

    # RT_ tables (Real-time data)
    "RT_AV": """
        CREATE TABLE IF NOT EXISTS RT_AV (
            RecordSpec TEXT,
            DataKubun TEXT,
            KettoNum TEXT,
            SaleHostName TEXT,
            SaleName TEXT,
            Price BIGINT,
            RecordDelimiter TEXT,
            PRIMARY KEY (KettoNum, SaleHostName, SaleName)
        )
    """,
    "RT_CC": """
        CREATE TABLE IF NOT EXISTS RT_CC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HappyoTime TEXT,
            AtoKyori INTEGER,
            AtoTruckCD TEXT,
            MaeKyori INTEGER,
            MaeTruckCD TEXT,
            JiyuCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_DM": """
        CREATE TABLE IF NOT EXISTS RT_DM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            MakeHM TEXT,
            Umaban INTEGER,
            DMTime TEXT,
            DMGosaP TEXT,
            DMGosaM TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_H1": """
        CREATE TABLE IF NOT EXISTS RT_H1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag1 TEXT,
            HatubaiFlag2 TEXT,
            HatubaiFlag3 TEXT,
            HatubaiFlag4 TEXT,
            HatubaiFlag5 TEXT,
            HatubaiFlag6 TEXT,
            HatubaiFlag7 TEXT,
            FukuChakuBaraiKey TEXT,
            HenkanUma TEXT,
            HenkanWaku TEXT,
            HenkanDoWaku TEXT,
            BetType TEXT,
            Kumi TEXT,
            Hyo BIGINT,
            Ninki INTEGER,
            TanHyoTotal BIGINT,
            FukuHyoTotal BIGINT,
            WakuHyoTotal BIGINT,
            UmarenHyoTotal BIGINT,
            WideHyoTotal BIGINT,
            UmatanHyoTotal BIGINT,
            SanrenfukuHyoTotal BIGINT,
            TanHenkanHyoTotal BIGINT,
            FukuHenkanHyoTotal BIGINT,
            WakuHenkanHyoTotal BIGINT,
            UmarenHenkanHyoTotal BIGINT,
            WideHenkanHyoTotal BIGINT,
            UmatanHenkanHyoTotal BIGINT,
            SanrenfukuHenkanHyoTotal BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, BetType, Kumi)
        )
    """,
    "RT_H6": """
        CREATE TABLE IF NOT EXISTS RT_H6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            HatubaiFlag TEXT,
            HenkanUma TEXT,
            SanrentanKumi TEXT,
            SanrentanHyo BIGINT,
            SanrentanNinki INTEGER,
            SanrentanHyoTotal BIGINT,
            SanrentanHenkanHyoTotal BIGINT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, SanrentanKumi)
        )
    """,
    "RT_HR": """
        CREATE TABLE IF NOT EXISTS RT_HR (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            FuseirituFlag1 INTEGER,
            FuseirituFlag2 INTEGER,
            FuseirituFlag3 INTEGER,
            FuseirituFlag4 INTEGER,
            FuseirituFlag5 INTEGER,
            FuseirituFlag6 INTEGER,
            FuseirituFlag7 INTEGER,
            FuseirituFlag8 INTEGER,
            FuseirituFlag9 INTEGER,
            TokubaraiFlag1 INTEGER,
            TokubaraiFlag2 INTEGER,
            TokubaraiFlag3 INTEGER,
            TokubaraiFlag4 INTEGER,
            TokubaraiFlag5 INTEGER,
            TokubaraiFlag6 INTEGER,
            TokubaraiFlag7 INTEGER,
            TokubaraiFlag8 INTEGER,
            TokubaraiFlag9 INTEGER,
            HenkanFlag1 INTEGER,
            HenkanFlag2 INTEGER,
            HenkanFlag3 INTEGER,
            HenkanFlag4 INTEGER,
            HenkanFlag5 INTEGER,
            HenkanFlag6 INTEGER,
            HenkanFlag7 INTEGER,
            HenkanFlag8 INTEGER,
            HenkanFlag9 INTEGER,
            HenkanUma1 TEXT,
            HenkanUma2 TEXT,
            HenkanUma3 TEXT,
            HenkanUma4 TEXT,
            HenkanUma5 TEXT,
            HenkanUma6 TEXT,
            HenkanUma7 TEXT,
            HenkanUma8 TEXT,
            HenkanUma9 TEXT,
            HenkanUma10 TEXT,
            HenkanUma11 TEXT,
            HenkanUma12 TEXT,
            HenkanUma13 TEXT,
            HenkanUma14 TEXT,
            HenkanUma15 TEXT,
            HenkanUma16 TEXT,
            HenkanUma17 TEXT,
            HenkanUma18 TEXT,
            HenkanUma19 TEXT,
            HenkanUma20 TEXT,
            HenkanUma21 TEXT,
            HenkanUma22 TEXT,
            HenkanUma23 TEXT,
            HenkanUma24 TEXT,
            HenkanUma25 TEXT,
            HenkanUma26 TEXT,
            HenkanUma27 TEXT,
            HenkanUma28 TEXT,
            HenkanWaku1 TEXT,
            HenkanWaku2 TEXT,
            HenkanWaku3 TEXT,
            HenkanWaku4 TEXT,
            HenkanWaku5 TEXT,
            HenkanWaku6 TEXT,
            HenkanWaku7 TEXT,
            HenkanWaku8 TEXT,
            HenkanDoWaku1 TEXT,
            HenkanDoWaku2 TEXT,
            HenkanDoWaku3 TEXT,
            HenkanDoWaku4 TEXT,
            HenkanDoWaku5 TEXT,
            HenkanDoWaku6 TEXT,
            HenkanDoWaku7 TEXT,
            HenkanDoWaku8 TEXT,
            TanUmaban TEXT,
            TanPay BIGINT,
            TanNinki INTEGER,
            TanUmaban2 TEXT,
            TanPay2 BIGINT,
            TanNinki2 INTEGER,
            TanUmaban3 TEXT,
            TanPay3 BIGINT,
            TanNinki3 INTEGER,
            FukuUmaban TEXT,
            FukuPay BIGINT,
            FukuNinki INTEGER,
            FukuUmaban2 TEXT,
            FukuPay2 BIGINT,
            FukuNinki2 INTEGER,
            FukuUmaban3 TEXT,
            FukuPay3 BIGINT,
            FukuNinki3 INTEGER,
            FukuUmaban4 TEXT,
            FukuPay4 BIGINT,
            FukuNinki4 INTEGER,
            FukuUmaban5 TEXT,
            FukuPay5 BIGINT,
            FukuNinki5 INTEGER,
            WakuKumi TEXT,
            WakuPay BIGINT,
            WakuNinki INTEGER,
            WakuKumi2 TEXT,
            WakuPay2 BIGINT,
            WakuNinki2 INTEGER,
            WakuKumi3 TEXT,
            WakuPay3 BIGINT,
            WakuNinki3 INTEGER,
            UmarenKumi TEXT,
            UmarenPay BIGINT,
            UmarenNinki INTEGER,
            UmarenKumi2 TEXT,
            UmarenPay2 BIGINT,
            UmarenNinki2 INTEGER,
            UmarenKumi3 TEXT,
            UmarenPay3 BIGINT,
            UmarenNinki3 INTEGER,
            WideKumi TEXT,
            WidePay BIGINT,
            WideNinki INTEGER,
            WideKumi2 TEXT,
            WidePay2 BIGINT,
            WideNinki2 INTEGER,
            WideKumi3 TEXT,
            WidePay3 BIGINT,
            WideNinki3 INTEGER,
            WideKumi4 TEXT,
            WidePay4 BIGINT,
            WideNinki4 INTEGER,
            WideKumi5 TEXT,
            WidePay5 BIGINT,
            WideNinki5 INTEGER,
            WideKumi6 TEXT,
            WidePay6 BIGINT,
            WideNinki6 INTEGER,
            WideKumi7 TEXT,
            WidePay7 BIGINT,
            WideNinki7 INTEGER,
            UmatanKumi TEXT,
            UmatanPay BIGINT,
            UmatanNinki INTEGER,
            UmatanKumi2 TEXT,
            UmatanPay2 BIGINT,
            UmatanNinki2 INTEGER,
            UmatanKumi3 TEXT,
            UmatanPay3 BIGINT,
            UmatanNinki3 INTEGER,
            UmatanKumi4 TEXT,
            UmatanPay4 BIGINT,
            UmatanNinki4 INTEGER,
            UmatanKumi5 TEXT,
            UmatanPay5 BIGINT,
            UmatanNinki5 INTEGER,
            UmatanKumi6 TEXT,
            UmatanPay6 BIGINT,
            UmatanNinki6 INTEGER,
            SanrenfukuKumi TEXT,
            SanrenfukuPay BIGINT,
            SanrenfukuNinki INTEGER,
            SanrenfukuKumi2 TEXT,
            SanrenfukuPay2 BIGINT,
            SanrenfukuNinki2 INTEGER,
            SanrenfukuKumi3 TEXT,
            SanrenfukuPay3 BIGINT,
            SanrenfukuNinki3 INTEGER,
            SanrentanKumi TEXT,
            SanrentanPay BIGINT,
            SanrentanNinki INTEGER,
            SanrentanKumi2 TEXT,
            SanrentanPay2 BIGINT,
            SanrentanNinki2 INTEGER,
            SanrentanKumi3 TEXT,
            SanrentanPay3 BIGINT,
            SanrentanNinki3 INTEGER,
            SanrentanKumi4 TEXT,
            SanrentanPay4 BIGINT,
            SanrentanNinki4 INTEGER,
            SanrentanKumi5 TEXT,
            SanrentanPay5 BIGINT,
            SanrentanNinki5 INTEGER,
            SanrentanKumi6 TEXT,
            SanrentanPay6 BIGINT,
            SanrentanNinki6 INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_JC": """
        CREATE TABLE IF NOT EXISTS RT_JC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HappyoTime TEXT,
            Umaban INTEGER,
            Bamei TEXT,
            AtoFutan NUMERIC(4,1),
            AtoKisyuCode TEXT,
            AtoKisyuName TEXT,
            AtoMinaraiCD TEXT,
            MaeFutan NUMERIC(4,1),
            MaeKisyuCode TEXT,
            MaeKisyuName TEXT,
            MaeMinaraiCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_O1": """
        CREATE TABLE IF NOT EXISTS RT_O1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            TanFlag TEXT,
            FukuFlag TEXT,
            WakurenFlag TEXT,
            FukuChakubaraiKey TEXT,
            Umaban INTEGER,
            TanOdds NUMERIC(8,1),
            TanNinki INTEGER,
            FukuUmaban INTEGER,
            FukuOddsLow NUMERIC(8,1),
            FukuOddsHigh NUMERIC(8,1),
            FukuNinki INTEGER,
            Kumi TEXT,
            WakurenOdds NUMERIC(8,1),
            WakurenNinki INTEGER,
            TanVote BIGINT,
            FukuVote BIGINT,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_O1_WAKU": """
        CREATE TABLE IF NOT EXISTS RT_O1_WAKU (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            WakurenFlag TEXT,
            Kumi TEXT,
            WakurenOdds NUMERIC(8,1),
            WakurenNinki INTEGER,
            WakurenVote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O2": """
        CREATE TABLE IF NOT EXISTS RT_O2 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmarenFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O3": """
        CREATE TABLE IF NOT EXISTS RT_O3 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            WideFlag TEXT,
            Kumi TEXT,
            OddsLow NUMERIC(8,1),
            OddsHigh NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O4": """
        CREATE TABLE IF NOT EXISTS RT_O4 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmatanFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O5": """
        CREATE TABLE IF NOT EXISTS RT_O5 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrenpukuFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_O6": """
        CREATE TABLE IF NOT EXISTS RT_O6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrentanFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "RT_RA": """
        CREATE TABLE IF NOT EXISTS RT_RA (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            YoubiCD TEXT,
            TokuNum TEXT,
            Hondai TEXT,
            Fukudai TEXT,
            Kakko TEXT,
            HondaiEng TEXT,
            FukudaiEng TEXT,
            KakkoEng TEXT,
            Ryakusyo10 TEXT,
            Ryakusyo6 TEXT,
            Ryakusyo3 TEXT,
            Kubun TEXT,
            Nkai TEXT,
            GradeCD TEXT,
            GradeCDBefore TEXT,
            SyubetuCD TEXT,
            KigoCD TEXT,
            JyuryoCD TEXT,
            JyokenCD1 TEXT,
            JyokenCD2 TEXT,
            JyokenCD3 TEXT,
            JyokenCD4 TEXT,
            JyokenCD5 TEXT,
            JyokenName TEXT,
            Kyori INTEGER,
            KyoriBefore INTEGER,
            TrackCD TEXT,
            TrackCDBefore TEXT,
            CourseKubunCD TEXT,
            CourseKubunCDBefore TEXT,
            Honsyokin1 BIGINT,
            Honsyokin2 BIGINT,
            Honsyokin3 BIGINT,
            Honsyokin4 BIGINT,
            Honsyokin5 BIGINT,
            Honsyokin6 BIGINT,
            Honsyokin7 BIGINT,
            HonsyokinBefore1 BIGINT,
            HonsyokinBefore2 BIGINT,
            HonsyokinBefore3 BIGINT,
            HonsyokinBefore4 BIGINT,
            HonsyokinBefore5 BIGINT,
            Fukasyokin1 BIGINT,
            Fukasyokin2 BIGINT,
            Fukasyokin3 BIGINT,
            Fukasyokin4 BIGINT,
            Fukasyokin5 BIGINT,
            FukasyokinBefore1 BIGINT,
            FukasyokinBefore2 BIGINT,
            FukasyokinBefore3 BIGINT,
            HassoTime TEXT,
            HassoTimeBefore TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            NyusenTosu INTEGER,
            TenkoCD TEXT,
            SibaBabaCD TEXT,
            DirtBabaCD TEXT,
            LapTime1 TEXT, LapTime2 TEXT, LapTime3 TEXT, LapTime4 TEXT, LapTime5 TEXT,
            LapTime6 TEXT, LapTime7 TEXT, LapTime8 TEXT, LapTime9 TEXT, LapTime10 TEXT,
            LapTime11 TEXT, LapTime12 TEXT, LapTime13 TEXT, LapTime14 TEXT, LapTime15 TEXT,
            LapTime16 TEXT, LapTime17 TEXT, LapTime18 TEXT, LapTime19 TEXT, LapTime20 TEXT,
            LapTime21 TEXT, LapTime22 TEXT, LapTime23 TEXT, LapTime24 TEXT, LapTime25 TEXT,
            SyogaiMileTime TEXT,
            Haron3F NUMERIC(4,1),
            Haron4F NUMERIC(4,1),
            Haron3L NUMERIC(4,1),
            Haron4L NUMERIC(4,1),
            Corner1 TEXT, Syukaisu1 TEXT, TsukaJyuni1 TEXT,
            Corner2 TEXT, Syukaisu2 TEXT, TsukaJyuni2 TEXT,
            Corner3 TEXT, Syukaisu3 TEXT, TsukaJyuni3 TEXT,
            Corner4 TEXT, Syukaisu4 TEXT, TsukaJyuni4 TEXT,
            RecordUpKubun TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    "RT_SE": """
        CREATE TABLE IF NOT EXISTS RT_SE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            Wakuban INTEGER,
            Umaban INTEGER,
            KettoNum TEXT,
            Bamei TEXT,
            UmaKigoCD TEXT,
            SexCD TEXT,
            HinsyuCD TEXT,
            KeiroCD TEXT,
            Barei INTEGER,
            TozaiCD TEXT,
            ChokyosiCode TEXT,
            ChokyosiRyakusyo TEXT,
            BanusiCode TEXT,
            BanusiName TEXT,
            Fukusyoku TEXT,
            Reserved_229 TEXT,
            Futan NUMERIC(4,1),
            FutanBefore NUMERIC(4,1),
            Blinker TEXT,
            Reserved_296 TEXT,
            KisyuCode TEXT,
            KisyuCodeBefore TEXT,
            KisyuRyakusyo TEXT,
            KisyuRyakusyoBefore TEXT,
            MinaraiCD TEXT,
            MinaraiCDBefore TEXT,
            BaTaijyu INTEGER,
            ZogenFugo TEXT,
            ZogenSa INTEGER,
            IJyoCD TEXT,
            NyusenJyuni INTEGER,
            KakuteiJyuni INTEGER,
            DochakuKubun TEXT,
            DochakuTosu INTEGER,
            Time NUMERIC(5,1),
            ChakusaCD TEXT,
            ChakusaCDP TEXT,
            ChakusaCDPP TEXT,
            Jyuni1c INTEGER,
            Jyuni2c INTEGER,
            Jyuni3c INTEGER,
            Jyuni4c INTEGER,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Honsyokin BIGINT,
            Fukasyokin BIGINT,
            Reserved_382 TEXT,
            Reserved_385 TEXT,
            HaronTimeL4 NUMERIC(4,1),
            HaronTimeL3 NUMERIC(4,1),
            KettoNum1 TEXT,
            Bamei1 TEXT,
            KettoNum2 TEXT,
            Bamei2 TEXT,
            KettoNum3 TEXT,
            Bamei3 TEXT,
            TimeDiff NUMERIC(5,1),
            RecordUpKubun TEXT,
            DMKubun TEXT,
            DMTime NUMERIC(6,1),
            DMGosaP NUMERIC(5,1),
            DMGosaM NUMERIC(5,1),
            DMJyuni INTEGER,
            KyakusituKubun TEXT,
            Reserved_462 TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_TC": """
        CREATE TABLE IF NOT EXISTS RT_TC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HappyoTime TEXT,
            AtoJi TEXT,
            AtoFun TEXT,
            MaeJi TEXT,
            MaeFun TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum)
        )
    """,
    # RT_RC: 騎手変更情報 (0B41) - リアルタイム用
    # NL_RCはレコード情報だが、JVRTOpenの0B41は騎手変更情報として別フォーマット
    "RT_RC": """
        CREATE TABLE IF NOT EXISTS RT_RC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            Umaban TEXT,
            KisyuCode TEXT,
            KisyuName TEXT,
            MaeKisyuCode TEXT,
            MaeKisyuName TEXT,
            HenkouJiyuCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_TM": """
        CREATE TABLE IF NOT EXISTS RT_TM (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            MakeHM TEXT,
            Umaban INTEGER,
            TMScore INTEGER,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban)
        )
    """,
    "RT_WE": """
        CREATE TABLE IF NOT EXISTS RT_WE (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            HappyoTime TEXT,
            HenkoID TEXT,
            TenkoState TEXT,
            SibaBabaState TEXT,
            DirtBabaState TEXT,
            TenkoState2 TEXT,
            SibaBabaState2 TEXT,
            DirtBabaState2 TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HenkoID)
        )
    """,
    "RT_WH": """
        CREATE TABLE IF NOT EXISTS RT_WH (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            HappyoTime TEXT,
            HenkoID TEXT,
            AtoTenkoCD TEXT,
            AtoSibaBabaCD TEXT,
            AtoDirtBabaCD TEXT,
            MaeTenkoCD TEXT,
            MaeSibaBabaCD TEXT,
            MaeDirtBabaCD TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, HappyoTime, HenkoID)
        )
    """,
    # ========================================
    # 時系列オッズテーブル (TS_O1-O6)
    # オッズの推移を記録するための専用テーブル
    # HassoTime + FetchedAt をPKに含めて複数時点のスナップショットを蓄積
    # ========================================
    "TS_O1": """
        CREATE TABLE IF NOT EXISTS TS_O1 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            TanFlag TEXT,
            FukuFlag TEXT,
            WakurenFlag TEXT,
            FukuChakubaraiKey TEXT,
            Umaban INTEGER,
            TanOdds NUMERIC(8,1),
            TanNinki INTEGER,
            FukuUmaban INTEGER,
            FukuOddsLow NUMERIC(8,1),
            FukuOddsHigh NUMERIC(8,1),
            FukuNinki INTEGER,
            Kumi TEXT,
            WakurenOdds NUMERIC(8,1),
            WakurenNinki INTEGER,
            TanVote BIGINT,
            FukuVote BIGINT,
            WakurenVote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Umaban, HassoTime, FetchedAt)
        )
    """,
    "TS_O1_WAKU": """
        CREATE TABLE IF NOT EXISTS TS_O1_WAKU (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            WakurenFlag TEXT,
            Kumi TEXT,
            WakurenOdds NUMERIC(8,1),
            WakurenNinki INTEGER,
            WakurenVote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime, FetchedAt)
        )
    """,
    "TS_O2": """
        CREATE TABLE IF NOT EXISTS TS_O2 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmarenFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime, FetchedAt)
        )
    """,
    "TS_O3": """
        CREATE TABLE IF NOT EXISTS TS_O3 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            WideFlag TEXT,
            Kumi TEXT,
            OddsLow NUMERIC(8,1),
            OddsHigh NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime, FetchedAt)
        )
    """,
    "TS_O4": """
        CREATE TABLE IF NOT EXISTS TS_O4 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            UmatanFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime, FetchedAt)
        )
    """,
    "TS_O5": """
        CREATE TABLE IF NOT EXISTS TS_O5 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrenpukuFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime, FetchedAt)
        )
    """,
    "TS_O6": """
        CREATE TABLE IF NOT EXISTS TS_O6 (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            Year INTEGER,
            MonthDay INTEGER,
            JyoCD TEXT,
            Kaiji INTEGER,
            Nichiji INTEGER,
            RaceNum INTEGER,
            HassoTime TEXT,
            TorokuTosu INTEGER,
            SyussoTosu INTEGER,
            SanrentanFlag TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            Vote BIGINT,
            FetchedAt TEXT,
            Source TEXT,
            PRIMARY KEY (Year, MonthDay, JyoCD, Kaiji, Nichiji, RaceNum, Kumi, HassoTime, FetchedAt)
        )
    """,
    "NL_NC": """
        CREATE TABLE IF NOT EXISTS NL_NC (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            JyoCD TEXT,
            JyoName TEXT,
            JyoName_Ryaku TEXT,
            JyoName_Eng TEXT,
            Address TEXT,
            TelNum TEXT,
            RecordDelimiter TEXT,
            PRIMARY KEY (JyoCD)
        )
    """,
    "NL_HA": """
        CREATE TABLE IF NOT EXISTS NL_HA (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KaisaiDate TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            TorokuTosu TEXT,
            SyussoTosu TEXT,
            HatsubaiFlag TEXT,
            Kumi TEXT,
            WakutanVote BIGINT,
            TotalVote BIGINT,
            PRIMARY KEY (KaisaiDate, JyoCD, Kaiji, Nichiji, RaceNum, Kumi)
        )
    """,
    "NL_NU": """
        CREATE TABLE IF NOT EXISTS NL_NU (
            RecordSpec TEXT,
            UmaID TEXT,
            TorokuNum TEXT,
            Reserved TEXT,
            BirthDate TEXT,
            Bamei TEXT,
            PRIMARY KEY (UmaID)
        )
    """,
    "NL_OA": """
        CREATE TABLE IF NOT EXISTS NL_OA (
            RecordSpec TEXT,
            DataKubun TEXT,
            MakeDate TEXT,
            KaisaiDate TEXT,
            JyoCD TEXT,
            Kaiji TEXT,
            Nichiji TEXT,
            RaceNum TEXT,
            OddsType TEXT,
            Kumi TEXT,
            Odds NUMERIC(8,1),
            Ninki INTEGER,
            PRIMARY KEY (KaisaiDate, JyoCD, Kaiji, Nichiji, RaceNum, OddsType, Kumi)
        )
    """
}


class SchemaManager:
    """Schema management for JLTSQL database.

    Manages table creation and schema operations.
    """

    def __init__(self, db: BaseDatabase):
        """Initialize schema manager.

        Args:
            db: Database instance
        """
        self.db = db

    def get_table_names(self) -> List[str]:
        """Get list of all table names in schema.

        Returns:
            List of table names
        """
        return list(SCHEMAS.keys())

    def create_table(self, table_name: str) -> bool:
        """Create single table.

        Args:
            table_name: Name of table to create

        Returns:
            True if successful, False otherwise
        """
        if table_name not in SCHEMAS:
            logger.error(f"Unknown table: {table_name}")
            return False

        try:
            schema_sql = SCHEMAS[table_name]
            self.db.execute(schema_sql)
            logger.info(f"Created table: {table_name}")
            return True
        except Exception as e:
            logger.error(f"Failed to create table {table_name}: {e}")
            return False

    def create_all_tables(self) -> Dict[str, bool]:
        """Create all tables defined in SCHEMAS.

        Returns:
            Dictionary mapping table names to success status
        """
        logger.info("Creating all tables...")
        results = {}

        for table_name, schema_sql in SCHEMAS.items():
            try:
                self.db.execute(schema_sql)
                logger.debug(f"Created table: {table_name}")
                results[table_name] = True
            except Exception as e:
                logger.error(f"Failed to create table {table_name}: {e}")
                results[table_name] = False

        success_count = sum(1 for v in results.values() if v)
        logger.info(f"Successfully created {success_count}/{len(SCHEMAS)} tables")
        return results

    def table_exists(self, table_name: str) -> bool:
        """Check if table exists in database.

        Args:
            table_name: Name of table to check

        Returns:
            True if table exists, False otherwise
        """
        return self.db.table_exists(table_name)

    def get_existing_tables(self) -> List[str]:
        """Get list of existing tables.

        Returns:
            List of table names that exist in database
        """
        existing = []
        for table_name in SCHEMAS.keys():
            if self.db.table_exists(table_name):
                existing.append(table_name)
        return existing

    def get_missing_tables(self) -> List[str]:
        """Get list of missing tables.

        Returns:
            List of table names that don't exist in database
        """
        missing = []
        for table_name in SCHEMAS.keys():
            if not self.db.table_exists(table_name):
                missing.append(table_name)
        return missing

    def apply_metadata_to_table(self, table_name: str) -> bool:
        """Apply metadata to a specific table.

        Args:
            table_name: Name of table to apply metadata to

        Returns:
            True if successful, False otherwise
        """
        from src.database.schema_metadata import TABLE_METADATA

        # Check if table exists in database
        if not self.db.table_exists(table_name):
            logger.warning(f"Table {table_name} does not exist")
            return False

        # Check if metadata is defined for this table
        if table_name not in TABLE_METADATA:
            logger.warning(f"No metadata defined for table {table_name}")
            return False

        metadata = TABLE_METADATA[table_name]
        db_type = self.db.get_db_type()

        try:
            if db_type == "sqlite":
                # SQLite: Use _metadata table
                # Create _metadata table if it doesn't exist
                self.db.execute("""
                    CREATE TABLE IF NOT EXISTS _metadata (
                        table_name TEXT NOT NULL,
                        column_name TEXT NOT NULL DEFAULT '',
                        description TEXT,
                        metadata_type TEXT NOT NULL DEFAULT 'column',
                        PRIMARY KEY (table_name, column_name)
                    )
                """)

                # Insert table description (column_name is empty string for table descriptions)
                self.db.execute(
                    """INSERT OR REPLACE INTO _metadata (table_name, column_name, description, metadata_type)
                       VALUES (?, '', ?, 'table')""",
                    (table_name, metadata.get("description", ""))
                )

                # Insert column descriptions
                for col in metadata.get("columns", []):
                    col_name = col.get("name", "")
                    col_desc = col.get("description", "")
                    if col_name:
                        self.db.execute(
                            """INSERT OR REPLACE INTO _metadata (table_name, column_name, description, metadata_type)
                               VALUES (?, ?, ?, 'column')""",
                            (table_name, col_name, col_desc)
                        )

            elif db_type == "postgresql":
                # PostgreSQL: Use COMMENT ON
                # Table comment
                table_desc = metadata.get("description", "").replace("'", "''")
                self.db.execute(f"COMMENT ON TABLE {table_name} IS '{table_desc}'")

                # Column comments
                for col in metadata.get("columns", []):
                    col_name = col.get("name", "")
                    col_desc = col.get("description", "").replace("'", "''")
                    if col_name:
                        # Use double quotes for column names with Japanese characters
                        self.db.execute(f'COMMENT ON COLUMN {table_name}."{col_name}" IS \'{col_desc}\'')

            logger.info(f"Applied metadata to table {table_name}")
            return True

        except Exception as e:
            logger.error(f"Failed to apply metadata to {table_name}: {e}")
            return False

    def get_table_metadata(self, table_name: str) -> dict:
        """Get metadata for a specific table.

        Args:
            table_name: Name of table

        Returns:
            Dictionary with table and column metadata
        """
        db_type = self.db.get_db_type()
        result = {"table": None, "columns": {}}

        try:
            if db_type == "sqlite":
                # Query _metadata table
                if not self.db.table_exists("_metadata"):
                    return result

                # Get table description (column_name is empty string)
                rows = self.db.fetch_all(
                    "SELECT description FROM _metadata WHERE table_name = ? AND column_name = ''",
                    (table_name,)
                )
                if rows:
                    result["table"] = rows[0]["description"]

                # Get column descriptions
                rows = self.db.fetch_all(
                    "SELECT column_name, description FROM _metadata WHERE table_name = ? AND column_name != ''",
                    (table_name,)
                )
                for row in rows:
                    result["columns"][row["column_name"]] = row["description"]

            elif db_type == "postgresql":
                # Query information_schema or pg_description
                # Implementation depends on specific database
                # For now, return empty (can be enhanced later)
                pass

        except Exception as e:
            logger.error(f"Failed to get metadata for {table_name}: {e}")

        return result

    def apply_all_metadata(self) -> Dict[str, bool]:
        """Apply metadata to all tables that have metadata defined.

        Returns:
            Dictionary mapping table names to success status
        """
        from src.database.schema_metadata import TABLE_METADATA

        results = {}
        for table_name in TABLE_METADATA.keys():
            results[table_name] = self.apply_metadata_to_table(table_name)

        success_count = sum(1 for v in results.values() if v)
        logger.info(f"Applied metadata to {success_count}/{len(results)} tables")
        return results


def create_all_tables(db: BaseDatabase) -> None:
    """Create all tables defined in SCHEMAS.

    Before creating tables, checks for schema mismatches in existing tables
    and recreates them if needed (e.g., when column definitions have changed).

    Args:
        db: Database instance
    """
    from src.database.migration import migrate_all_tables

    logger.info("Creating tables...")

    # Check and migrate existing tables with mismatched schemas
    migrate_all_tables(db, SCHEMAS)

    for table_name, schema_sql in SCHEMAS.items():
        try:
            db.execute(schema_sql)
            logger.debug(f"Created table: {table_name}")
        except Exception as e:
            logger.error(f"Failed to create table {table_name}: {e}")
            raise
    logger.info(f"Successfully created {len(SCHEMAS)} tables")